<script src="/dist/bundle.js?mb_version=<?=MB_VERSION?>"></script>
<script src="/dist/ruffle/ruffle.js?mb_version=<?=MB_VERSION?>"></script>
<script src="/dist/tegaki/tegaki.js?mb_version=<?=MB_VERSION?>"></script>
<script src="/dist/chiptune2js/libopenmpt.js?mb_version=<?=MB_VERSION?>"></script>
<script src="/dist/chiptune2js/chiptune2.js?mb_version=<?=MB_VERSION?>"></script>
<?php
  if (MB_CAPTCHA_HCAPTCHA_SITE != null) {
    echo '<script src="https://js.hcaptcha.com/1/api.js" async defer></script>';
  }
?>
