<table>
  <tr>
    <th>Username</th>
    <th>Role</th>
    <th>Last Active</th>
  </tr>
  <tr>
    <?php
      foreach ($account_details as $account) {
        $lastactive = strftime(MB_DATEFORMAT, $account['lastactive']);

        echo "<tr>";
        echo "<td> $account[username] </td>";
        echo "<td> $account[role] </td>";
        echo "<td> $lastactive </td>";
        echo "</tr>";
      }
      ?>
  </tr>
</table>
