<form id="csamhashform" class="form-manage" method="post">
  <table class="form-manage-table">
    <thead>
      <tr>
        <th>id</th>
        <th>sha256</th>
        <th>type</th>
        <th>algorithm</th>
        <th>hash</th>
        <th>quality</th>
        <th>originator</th>
        <th>timestamp</th>
      </tr>
    </thead>
    <tbody>
      <?php
        foreach ($rows as $row) {
          $timestamp = date(MB_DATEFORMAT, $row['timestamp']);

          echo "
            <tr>
              <td>{$row['id']}</td>
              <td>{$row['sha256']}</td>
              <td>{$row['type']}</td>
              <td>{$row['algorithm']}</td>
              <td>{$row['hash']}</td>
              <td>{$row['quality']}</td>
              <td>{$row['originator']}</td>
              <td>{$timestamp}</td>
            </tr>
          ";
        }
      ?>
    </tbody>
  </table>
</form>
