<form id="importform" class="manageform" method="post" action="import">
  <fieldset id="sourcedb" class="manageform-fieldset">
    <legend>Source database</legend>
    <div class="manageform-group">
      <label for="db_name">DB name</label>
      <input type="text" name="db_name">
    </div>
    <div class="manageform-group">
      <label for="db_user">DB user</label>
      <input type="text" name="db_user">
    </div>
    <div class="manageform-group">
      <label for="db_pass">DB pass</label>
      <input type="password" name="db_pass">
    </div>
  </fieldset>
  <fieldset id="sourcetable" class="manageform-fieldset">
    <legend>Source table</legend>
    <div class="manageform-group">
      <label for="table_name">TABLE name</label>
      <input type="text" name="table_name">
    </div>
    <div class="manageform-group">
      <label for="table_type">TABLE type</label>
      <?php
        $select_input = '<select id="table_type" name="table_type">';
        $select_options = '<option value=""></option>';
        foreach (MB_IMPORT_TABLE_TYPES as $key => $val) {
          $select_options .= "<option value='{$key}'>{$val}</option>";
        }
        echo $select_input . $select_options . '</select>';
      ?>
    </div>
  </fieldset>
  <fieldset id="targetboard" class="manageform-fieldset">
    <legend>Target board</legend>
    <div class="manageform-group">
      <label for="board_id">BOARD id</label>
      <?php
        $select_input = '<select id="board_id" name="board_id">';
        $select_options = '<option value=""></option>';
        foreach (MB_BOARDS as $key => $val) {
          if ($val['type'] === 'main') {
            continue;
          }
          
          $select_options .= "<option value='{$key}'>/{$key}/ - {$val['name']}</option>";
        }
        echo $select_input . $select_options . '</select>';
      ?>
    </div>
  </fieldset>
  <div class="manageform-group" style="text-align: right">
		<input type="submit" value="Import">
  </div>
  <div class="manageform-results">
    <b><?=$status?></b>
  </div>
</form>
