<form id="form-login" class="form-login form" method="post" action="login">
  <table>
    <tbody>
      <tr>
        <td class="form-label">
          <label for="username">Username</label>
        </td>
        <td>
          <input type="text" name="username">
        </td>
      </tr>
      <tr>
        <td class="form-label">
          <label for="password">Password</label>
        </td>
        <td>
          <input type="password" name="password">
		      <input type="submit" value="Log In">
        </td>
      </tr>
      <?php
        if (MB_CAPTCHA_LOGIN) {
          $captcha = MB_CAPTCHA_HCAPTCHA_SITE;

          echo "
            <tr>
              <td class='form-label'>
                <label for='captcha'>CAPTCHA</label>
              </td>
              <td>
                <div class='h-captcha' data-sitekey='{$captcha}'></div>
              </td>
            </tr>
          ";
        }
      ?>
    </tbody>
  </table>
</form>
