<div id="menubar" class="menubar">
  <div id="boardmenu" class="boardmenu">
    <?php
      $user_role = funcs_manage_get_role();
      
      echo $user_role === MB_ROLE_SUPERADMIN ? "[<a href='?route=rebuild'>Rebuild</a>]\n"   : '';
      echo $user_role === MB_ROLE_SUPERADMIN ? "[<a href='?route=import'>Import</a>]\n"     : '';
      echo $user_role === MB_ROLE_SUPERADMIN ? "[<a href='?route=accounts'>Accounts</a>]\n" : '';
    ?>
    [<a href="?route=logs">Logs</a>]
    [<a href="?route=csam_hashes">CSAM Hashes</a>]
    [<a href="?route=bans">Bans</a>]
    [<a href="?route=posts">Posts</a>]
    [<a href="?route=threads">Threads</a>]
    [<a href="?route=reports">Reports</a>]
    [<a href="logout">Log out</a>]
    [<a href="/">Return</a>]
    <?=$this->fetch('common/stylepicker.phtml')?>
  </div>
</div>
