<div class="menubar">
  <div class="boardmenu">
    <?php
      $user_role = funcs_manage_get_role();
      
      echo $user_role === MB_ROLE_SUPERADMIN ? "[<a href='?route=accounts'>Accounts</a>]\n" : '';
      echo $user_role === MB_ROLE_SUPERADMIN ? "[<a href='?route=rebuild'>Rebuild</a>]\n"   : '';
      echo $user_role === MB_ROLE_SUPERADMIN ? "[<a href='?route=import'>Import</a>]\n"     : '';
    ?>
    [<a href="logout">Log out</a>]
    [<a href="/">Return</a>]
    <?=$this->fetch('common/stylepicker.phtml')?>
  </div>
</div>
