<div class="menubar">
  <div class="boardmenu">
    <?php
      $user_role = funcs_common_get_role();
      
      echo $user_role === MB_ROLE_SUPERADMIN ? '[<a href="?route=accounts">Accounts</a>]' : '';
      echo $user_role === MB_ROLE_SUPERADMIN ? '[<a href="?route=rebuild">Rebuild</a>]'   : '';
      echo $user_role === MB_ROLE_SUPERADMIN ? '[<a href="?route=import">Import</a>]'     : '';
    ?>
    [<a href="logout">Log out</a>]
    [<a href="/">Return</a>]
  </div>
</div>
