<form id="rebuildform" class="manageform" method="post" action="rebuild">
  <fieldset id="targetboard" class="manageform-fieldset">
    <legend>Target board</legend>
    <div class="manageform-group">
      <label for="board_id">BOARD id</label>
      <?php
        $select_input = '<select id="board_id" name="board_id">';
        $select_options = '<option value=""></option>';
        foreach (MB_BOARDS as $key => $val) {
          if ($val['type'] === 'main') {
            continue;
          }
          
          $select_options .= "<option value='{$key}'>/{$key}/ - {$val['name']}</option>";
        }
        echo $select_input . $select_options . '</select>';
      ?>
    </div>
  </fieldset>
  <div class="manageform-group" style="text-align: right">
		<input type="submit" value="Rebuild">
  </div>
  <div class="manageform-results">
    <b><?=$status?></b>
  </div>
</form>
