<form id="banform" class="form-manage" method="post">
  <table class="form-manage-table">
    <thead>
      <tr>
        <th><?=__('manage.th.id')?></th>
        <th><?=__('manage.th.ip')?></th>
        <th><?=__('manage.th.timestamp')?></th>
        <th><?=__('manage.th.expire')?></th>
        <th><?=__('manage.th.reason')?></th>
        <th><?=__('manage.th.imported')?></th>
      </tr>
    </thead>
    <tbody>
      <?php
        foreach ($bans as $ban) {
          $timestamp = date(MB_DATEFORMAT, $ban['timestamp']);
          $expire = date(MB_DATEFORMAT, $ban['expire']);

          echo "
            <tr>
              <td>{$ban['id']}</td>
              <td>{$ban['ip_rendered']}</td>
              <td>{$timestamp}</td>
              <td>{$expire}</td>
              <td>{$ban['reason']}</td>
              <td>{$ban['imported']}</td>
            </tr>
          ";
        }
      ?>
    </tbody>
  </table>
</form>
