<form id="form-edit-ban" class="form-manage form" method="post" action="/manage/edit_ban?route=bans">
  <?= funcs_common_csrf_field() ?>
  <input type="hidden" name="id" value="<?= htmlspecialchars($ban['id'], ENT_QUOTES, 'UTF-8') ?>">
  <table>
    <tbody>
      <tr>
        <td class="form-label">
          <label><?= __('manage.editbanform.id') ?></label>
        </td>
        <td>
          <?= htmlspecialchars($ban['id'], ENT_QUOTES, 'UTF-8') ?>
        </td>
      </tr>
      <tr>
        <td class="form-label">
          <label><?= __('manage.editbanform.ip') ?></label>
        </td>
        <td>
          <?= $ban['ip_rendered'] ?>
        </td>
      </tr>
      <tr>
        <td class="form-label">
          <label><?= __('manage.editbanform.timestamp') ?></label>
        </td>
        <td>
          <?= date(MB_DATEFORMAT, $ban['timestamp']) ?>
        </td>
      </tr>
      <tr>
        <td class="form-label">
          <label><?= __('manage.editbanform.expire') ?></label>
        </td>
        <td>
          <?= date(MB_DATEFORMAT, $ban['expire']) ?>
        </td>
      </tr>
      <tr>
        <td class="form-label">
          <label for="duration"><?= __('manage.editbanform.duration') ?></label>
        </td>
        <td>
          <input type="number" name="duration" value="<?= max(0, (int) ceil(($ban['expire'] - time()) / 60)) ?>" placeholder="<?= __('manage.ban_minutes') ?>">
          <?= __('manage.editbanform.duration_hint') ?>
        </td>
      </tr>
      <tr>
        <td class="form-label">
          <label for="reason"><?= __('manage.editbanform.reason') ?></label>
        </td>
        <td>
          <input type="text" name="reason" autocomplete="off" value="<?= $ban['reason'] ?>">
          <input type="submit" name="submit" value="<?= __('manage.editbanform.submit') ?>">
        </td>
      </tr>
      <tr>
        <td class="form-label">
          <label for="comment"><?= __('manage.editbanform.comment') ?></label>
        </td>
        <td>
          <input type="text" name="comment" autocomplete="off" value="<?= $ban['comment'] ?? '' ?>">
        </td>
      </tr>
      <tr>
        <td class="form-label">
          <label><?= __('manage.editbanform.edit_options') ?></label>
        </td>
        <td>
          <input type="submit" value="<?= __('manage.delete_ban') ?>" formaction="/manage/delete_ban?route=bans" onclick="return confirm('<?= __('manage.editbanform.delete_confirm') ?>');">
        </td>
      </tr>
    </tbody>
  </table>
</form>
