<form id="form-import" class="form-import form" method="post" action="import">
  <?=funcs_common_csrf_field()?>
  <fieldset id="form-import-source-db">
    <legend><?=__('manage.source_db')?></legend>
    <table>
      <tbody>
        <tr>
          <td class="form-label">
            <label for="db_name"><?=__('manage.db_name')?></label>
          </td>
          <td>
            <input type="text" name="db_name">
          </td>
        </tr>
        <tr>
          <td class="form-label">
            <label for="db_user"><?=__('manage.db_user')?></label>
          </td>
          <td>
            <input type="text" name="db_user">
          </td>
        </tr>
        <tr>
          <td class="form-label">
            <label for="db_pass"><?=__('manage.db_pass')?></label>
          </td>
          <td>
            <input type="password" name="db_pass">
          </td>
        </tr>
      </tbody>
    </table>
  </fieldset>
  <fieldset id="form-import-source-table">
    <legend><?=__('manage.source_table')?></legend>
    <table>
      <tbody>
        <tr>
          <td class="form-label">
            <label for="table_name"><?=__('manage.table_name')?></label>
          </td>
          <td>
            <input type="text" name="table_name">
          </td>
        </tr>
        <tr>
          <td class="form-label">
            <label for="table_type"><?=__('manage.table_type')?></label>
          </td>
          <td>
            <?php
              $options = '<option value=""></option>';
              foreach (MB_IMPORT_TABLE_TYPES as $key => $val) {
                $options .= "<option value='{$key}'>{$val}</option>";
              }

              echo "<select id='table_type' name='table_type'>{$options}</select>";
            ?>
          </td>
        </tr>
      </tbody>
    </table>
  </fieldset>
  <fieldset id="form-import-target-board">
    <legend><?=__('manage.target_board')?></legend>
    <table>
      <tbody>
        <tr>
          <td class="form-label">
            <label for="board_id"><?=__('manage.board_id')?></label>
          </td>
          <td>
            <?php
              $options = '<option value=""></option>';
              foreach (MB_BOARDS as $key => $val) {
                if ($val['type'] === 'main') {
                  continue;
                }

                $options .= "<option value='{$key}'>/{$key}/ - {$val['name']}</option>";
              }

              echo "<select id='board_id' name='board_id'>{$options}</select>";
            ?>
          </td>
        </tr>
      </tbody>
    </table>
  </fieldset>
  <table>
    <tbody>
      <tr>
        <td class="form-label">
          <label><?=__('manage.status')?></label>
        </td>
        <td>
          <b><?=$status?></b>
        </td>
      </tr>
      <tr>
        <td class="form-label">
          <label><?=__('form.submit')?></label>
        </td>
        <td>
	        <input type="submit" value="<?=__('manage.import')?>">
        </td>
      </tr>
    </tbody>
  </table>
</form>
