<form id="form-import" class="form-import form" method="post" action="import">
  <fieldset id="form-import-source-db">
    <legend>Source database</legend>
    <table>
      <tbody>
        <tr>
          <td class="form-label">
            <label for="db_name">DB name</label>
          </td>
          <td>
            <input type="text" name="db_name">
          </td>
        </tr>
        <tr>
          <td class="form-label">
            <label for="db_user">DB user</label>
          </td>
          <td>
            <input type="text" name="db_user">
          </td>
        </tr>
        <tr>
          <td class="form-label">
            <label for="db_pass">DB pass</label>
          </td>
          <td>
            <input type="password" name="db_pass">
          </td>
        </tr>
      </tbody>
    </table>
  </fieldset>
  <fieldset id="form-import-source-table">
    <legend>Source table</legend>
    <table>
      <tbody>
        <tr>
          <td class="form-label">
            <label for="table_name">TABLE name</label>
          </td>
          <td>
            <input type="text" name="table_name">
          </td>
        </tr>
        <tr>
          <td class="form-label">
            <label for="table_type">TABLE type</label>
          </td>
          <td>
            <?php
              $options = '<option value=""></option>';
              foreach (MB_IMPORT_TABLE_TYPES as $key => $val) {
                $options .= "<option value='{$key}'>{$val}</option>";
              }

              echo "<select id='table_type' name='table_type'>{$options}</select>";
            ?>
          </td>
        </tr>
      </tbody>
    </table>
  </fieldset>
  <fieldset id="form-import-target-board">
    <legend>Target board</legend>
    <table>
      <tbody>
        <tr>
          <td class="form-label">
            <label for="board_id">BOARD id</label>
          </td>
          <td>
            <?php
              $options = '<option value=""></option>';
              foreach (MB_BOARDS as $key => $val) {
                if ($val['type'] === 'main') {
                  continue;
                }

                $options .= "<option value='{$key}'>/{$key}/ - {$val['name']}</option>";
              }

              echo "<select id='board_id' name='board_id'>{$options}</select>";
            ?>
          </td>
        </tr>
      </tbody>
    </table>
  </fieldset>
  <table>
    <tbody>
      <tr>
        <td class="form-label">
          <label>STATUS</label>
        </td>
        <td>
          <b><?=$status?></b>
        </td>
      </tr>
      <tr>
        <td class="form-label">
          <label>Submit</label>
        </td>
        <td>
	        <input type="submit" value="Import">
        </td>
      </tr>
    </tbody>
  </table>
</form>
