<form id="logform" class="form-manage" method="post">
  <table class="form-manage-table">
    <thead>
      <tr>
        <th><?=__('manage.th.id')?></th>
        <th><?=__('manage.th.ip')?></th>
        <th><?=__('manage.th.timestamp')?></th>
        <th><?=__('manage.th.username')?></th>
        <th><?=__('manage.th.message')?></th>
      </tr>
    </thead>
    <tbody>
      <?php
        foreach ($logs as $log) {
          $timestamp = date(MB_DATEFORMAT, $log['timestamp']);

          echo "
            <tr>
              <td>{$log['id']}</td>
              <td>{$log['ip_rendered']}</td>
              <td>{$timestamp}</td>
              <td>{$log['username_rendered']}</td>
              <td>{$log['message']}</td>
            </tr>
          ";
        }
      ?>
    </tbody>
  </table>
</form>
