<form id="form-login" class="form-login form" method="post" action="login">
  <?=funcs_common_csrf_field()?>
  <table>
    <tbody>
      <tr>
        <td class="form-label">
          <label for="username"><?=__('manage.username')?></label>
        </td>
        <td>
          <input type="text" name="username">
        </td>
      </tr>
      <tr>
        <td class="form-label">
          <label for="password"><?=__('manage.password')?></label>
        </td>
        <td>
          <input type="password" name="password">
		      <input type="submit" value="<?=__('manage.log_in')?>">
        </td>
      </tr>
      <?php
        if (MB_CAPTCHA_LOGIN) {
          $captcha = MB_CAPTCHA_HCAPTCHA_SITE;
          $t_captcha = __('form.captcha');

          echo "
            <tr>
              <td class='form-label'>
                <label for='captcha'>{$t_captcha}</label>
              </td>
              <td>
                <div class='h-captcha' data-sitekey='{$captcha}'></div>
              </td>
            </tr>
          ";
        }
      ?>
    </tbody>
  </table>
</form>
