<?php
  if (isset($post['file_rendered']) && !empty($post['file_rendered'])) {
    $thumb_src = "{$post['thumb']}";
    $thumb_width = $post['thumb_width'];
    $thumb_height = $post['thumb_height'];
    $thumb_id = $context !== 'preview' ? "id='thumb-{$post['board_id']}-{$post['post_id']}'" : '';

    if ($post['embed'] === 0) {
      $album_id = $context !== 'preview' && isset($post['audio_album']) ? "id='album-{$post['board_id']}-{$post['post_id']}'" : '';
      $file_meta = '';
      if (isset($post['file_mime']) && $post['file_mime'] === 'application/x-tegaki' && isset($post['file_meta'])) {
        $fmjson = json_decode($post['file_meta'], true);
        $duration = $fmjson['end_timestamp'] - $fmjson['start_timestamp'];
        $file_meta = "{$post['file_size_formatted']}, ".
          "Tool: Tegaki {$fmjson['tegaki_version_major']}.{$fmjson['tegaki_version_minor']}.{$fmjson['tegaki_version_patch']}, ".
          "Duration: {$duration}s, ".
          "{$fmjson['canvas_width']}x{$fmjson['canvas_height']}, ".
          "{$post['file_original']}, ".
          "<a href='{$fmjson['tgk_png_file_rendered']}' target='_blank'>PNG</a>";
      } else {
        $file_meta = "{$post['file_size_formatted']}, {$post['image_width']}x{$post['image_height']}, {$post['file_original']}";
      }

      $t_file = __('file.file');
      echo "
        <div class='file-info break-words'>
          {$t_file} <a href='{$post['file_rendered']}' target='_blank'>{$post['file_rendered']}</a>
          -
          ({$file_meta})
        </div>
        <div class='file-thumb'>
          <a class='file-thumb-href' href='{$post['file_rendered']}' target='_blank'>
            <img {$thumb_id} class='file-thumb-img' src='{$thumb_src}' width='{$thumb_width}' height='{$thumb_height}' loading='lazy'>
          </a>
        </div>
        <div class='file-data' style='display:none;'></div>
        <div {$album_id} class='audio-album' style='display:none;'>{$post['audio_album']}</div>
      ";
    } else {
      $t_embed = __('file.embed');
      $t_embedded_url = __('file.embedded_url');
      echo "
        <div class='file-info break-words'>
          {$t_embed} <a href='{$post['file_hex']}' target='_blank'>{$post['file_original']}</a>
          -
          ({$post['image_width']}x{$post['image_height']}, {$t_embedded_url})
        </div>
        <div class='file-thumb'>
          <a class='file-thumb-href' href='{$post['file_hex']}' target='_blank'>
            <img {$thumb_id} class='file-thumb-img' src='{$thumb_src}' width='{$thumb_width}' height='{$thumb_height}' loading='lazy'>
          </a>
        </div>
        <div class='file-data' style='display:none;'>{$post['file_rendered']}</div>
      ";
    }
  }
?>
