<form id="form-refresh" class="form-refresh form" method="post" action="refresh">
  <?=funcs_common_csrf_field()?>
  <fieldset id="form-refresh-target-board">
    <legend><?=__('manage.target_board')?></legend>
    <table>
      <tbody>
        <tr>
          <td class="form-label">
            <label for="board_id"><?=__('manage.board_id')?></label>
          </td>
          <td>
            <?php
              $options = '<option value=""></option>';
              foreach (MB_BOARDS as $key => $val) {
                $options .= "<option value='{$key}'>/{$key}/ - {$val['name']}</option>";
              }

              echo "<select id='board_id' name='board_id'>{$options}</select>";
            ?>
          </td>
        </tr>
      </tbody>
    </table>
  </fieldset>
  <table>
    <tbody>
      <tr>
        <td class="form-label">
          <label><?=__('manage.status')?></label>
        </td>
        <td>
          <b><?=$status?></b>
        </td>
      </tr>
      <tr>
        <td class="form-label">
          <label><?=__('form.submit')?></label>
        </td>
        <td>
	        <input type="submit" value="<?=__('manage.refresh')?>">
        </td>
      </tr>
    </tbody>
  </table>
</form>
