<form id="reportform" class="form-manage" method="post">
  <?=funcs_common_csrf_field()?>
  <table>
    <tbody>
      <tr>
        <td class="form-label">
          <label><?=__('manage.status')?></label>
        </td>
        <td>
          <b><?=$status?></b>
        </td>
      </tr>
      <tr>
        <td class="form-label">
          <label><?=__('manage.selected')?></label>
        </td>
        <td>
	        <input type="submit" value="<?=__('manage.delete_post')?>" formaction="delete?<?=http_build_query($_GET)?>">
	        <input type="submit" value="<?=__('manage.ban_ip')?>" formaction="ban?<?=http_build_query($_GET)?>">
          <input type="number" name="duration" placeholder="<?=__('manage.ban_minutes')?>">
          <input type="text" name="reason" placeholder="<?=__('manage.ban_reason')?>">
          <label><input type="checkbox" name="capture"> <?=__('manage.ban_capture')?></label>
	        <input type="submit" value="<?=__('manage.mark_csam')?>" formaction="csam_scanner/cp?<?=http_build_query($_GET)?>">
	        <input type="submit" value="<?=__('manage.toggle_lock')?>" formaction="toggle_lock?<?=http_build_query($_GET)?>">
	        <input type="submit" value="<?=__('manage.toggle_sticky')?>" formaction="toggle_sticky?<?=http_build_query($_GET)?>">
	        <input type="submit" value="<?=__('manage.approve_report')?>" formaction="approve?<?=http_build_query($_GET)?>">
        </td>
      </tr>
    </tbody>
  </table>
  <table class="form-manage-table">
    <thead>
      <tr>
        <th></th>
        <th><?=__('manage.th.id')?></th>
        <th><?=__('manage.th.ip')?></th>
        <th><?=__('manage.th.timestamp')?></th>
        <th><?=__('manage.th.board_id')?></th>
        <th><?=__('manage.th.post_id')?></th>
        <th><?=__('manage.th.type')?></th>
        <th><?=__('manage.th.reason')?></th>
        <th><?=__('manage.th.imported')?></th>
        <th><?=__('manage.th.post_ip')?></th>
        <th><?=__('manage.th.post_deleted')?></th>
        <th><?=__('manage.th.post_imported')?></th>
        <th><?=__('manage.th.preview')?></th>
      </tr>
    </thead>
    <tbody>
      <?php
        foreach ($reports as $report) {
          $preview = '';
          if ($report['parent_id'] == 0) {
            $preview = $this->render(__DIR__ . '/post_preview_op.phtml', ['post' => $report]);
          } else {
            $preview = $this->render(__DIR__ . '/post_preview_reply.phtml', ['post' => $report]);
          }

          $timestamp = date(MB_DATEFORMAT, $report['r_timestamp']);
          $imported = $report['r_imported'] === 1 ? '<b>TRUE</b>' : 'FALSE';
          $post_deleted = $report['deleted'] === 1 ? '<b>TRUE</b>' : 'FALSE';
          $post_imported = $report['imported'] === 1 ? '<b>TRUE</b>' : 'FALSE';

          echo "
            <tr>
              <td><input type=\"checkbox\" name=\"select[]\" value=\"{$report['board_id']}/{$report['post_id']}\"></td>
              <td>{$report['r_id']}</td>
              <td>{$report['r_ip_rendered']}</td>
              <td>{$timestamp}</td>
              <td>/{$report['r_board_id']}/</td>
              <td>{$report['r_post_id']}</td>
              <td>{$report['r_type']}</td>
              <td>" . htmlspecialchars($report['r_reason']) . "</td>
              <td>{$imported}</td>
              <td>{$report['ip_rendered']}</td>
              <td>{$post_deleted}</td>
              <td>{$post_imported}</td>
              <td>{$preview}</td>
            </tr>
          ";
        }
      ?>
    </tbody>
  </table>
</form>
