<!DOCTYPE html>
<html>
  <head>
    <?=$this->render(__ROOT__ . '/common/templates/meta.phtml')?>
    <?=$this->render(__ROOT__ . '/common/templates/styles.phtml')?>
    <?=$this->render(__ROOT__ . '/common/templates/scripts.phtml')?>
    <title><?=$site_name?> - <?=$site_desc?></title>
  </head>
  <body>
    <div id="menubar" class="menubar">
			<div id="boardmenu" class="boardmenu">
        [<a href="/">Home</a>]
        <?php
          if (in_array('bans', MB_MODULES)) {
            echo '[<a href="/bans/">Bans</a>]';
          }
        ?>
        [<a href="/manage/">Manage</a>]
			</div>
    </div>
    <?=$this->render(__ROOT__ . '/common/templates/header.phtml', ['h_title' => "{$site_name}", 'h_subtitle' => '', 'h_logo' => 'logo.png'])?>

    <div class="page-root container-centered">
      <div class="box-container">
        <div class="box">
          <div class="box-title">Boards</div>
          <div class="box-content">
            <table>
              <tr style="display: none">
                <th>col1</th>
                <th>col2</th>
                <th>col3</th>
                <th>col4</th>
              </tr>
              <?php
                $board_table_n = 0;
                foreach (MB_BOARDS as $key => $board) {
                  if (isset($board['hidden']) && $board['hidden'] == true) {
                    continue;
                  }

                  if ($board_table_n % 4 === 0) {
                    echo '<tr>';
                  }

                  $nsfw = isset($board['nsfw']) && $board['nsfw'] === true ? '<span class="nsfw">(NSFW)</span>' : '';
                  echo "<td><a href='/{$board['id']}/'>{$board['name']}</a> {$nsfw}</td>";

                  if ($board_table_n % 4 === 3) {
                    echo '</tr>';
                  }

                  $board_table_n++;
                }
                if ($board_table_n % 4 !== 0) {
                  echo '</tr>';
                }
              ?>
            </table>
          </div>
        </div>
      </div>
      <div class="box-container">
        <div class="box">
          <div class="box-title">Stats</div>
          <div class="box-content">
            <table>
              <tr style="display: none">
                <th>col1</th>
                <th>col2</th>
                <th>col3</th>
              </tr>
              <tr>
                <?php
                  $total_posts = number_format($site_stats['total_posts'] ?? 0, 0, '.', ',');
                  $current_posts = number_format($site_stats['current_posts'] ?? 0, 0, '.', ',');
                  $unique_posters = number_format($site_stats['unique_posters'] ?? 0, 0, '.', ',');

                  echo "<td><strong>Total Posts: </strong>{$total_posts}</td>";
                  echo "<td><strong>Current Posts: </strong>{$current_posts}</td>";
                  echo "<td><strong>Unique Posters: </strong>{$unique_posters}</td>";
                ?>
              </tr>
              <tr>
                <?php
                  require_once __ROOT__ . '/common/funcs_common.php';

                  $imported_posts = number_format($site_stats['imported_posts'] ?? 0, 0, '.', ',');
                  $current_files = number_format($site_stats['current_files'] ?? 0, 0, '.', ',');
                  $active_content = funcs_common_human_filesize($site_stats['active_content'] ?? 0);

                  echo "<td><strong>Imported Posts: </strong>{$imported_posts}</td>";
                  echo "<td><strong>Current Files: </strong>{$current_files}</td>";
                  echo "<td><strong>Active Content: </strong>{$active_content}</td>";
                ?>
              </tr>
            </table>
          </div>
        </div>
      </div>
      <div class="box-container">
        <div class="box">
          <div class="box-title">Rules</div>
          <div class="box-content">
            <?=MB_SITE_RULES?>
          </div>
        </div>
      </div>
    </div>
    <hr>
    <div class="container-centered">
      <?=$this->render(__ROOT__ . '/common/templates/footer.phtml')?>
    </div>
  </body>
</html>
