<!DOCTYPE html>
<html>
  <head>
    <?=$this->fetch('common/meta.phtml')?>
    <?=$this->fetch('common/styles.phtml')?>
    <?=$this->fetch('common/scripts.phtml')?>
    <title>/<?=$board['id']?>/</title>
  </head>
  <body>
    <?=$this->fetch('board/menubar.phtml', ['board_id' => $board['id'], 'thread_id' => null])?>
    <?=$this->fetch('common/banner.phtml')?>
    <hr>
    <?=$this->fetch('common/header.phtml', ['h_title' => "/{$board['id']}/ - {$board['name']}", 'h_subtitle' => $board['desc']])?>
    <hr>
    <div id="form-post-container" class="container-centered">
      <?=$this->fetch('board/postform.phtml', ['context' => 'board', 'board' => $board, 'action' => "/{$board['id']}"])?>
    </div>
    <hr>
    <div id="navlinks-top" class="navlinks">
      [<a id="navlinks-top-catalog" href="/<?=$board['id']?>/catalog/">Catalog</a>]
      [<a id="navlinks-top-refresh" href="./">Refresh</a>]
    </div>
    <hr>
    <?=$this->fetch('board/deleteform.phtml', ['context' => 'board', 'board' => $board, 'threads' => $threads])?>
    <?=$this->fetch('common/pagetable.phtml', ['page' => $page, 'page_n' => $page_n])?>
    <div class="container-centered">
      <?=$this->fetch('common/footer.phtml')?>
    </div>
  </body>
</html>
