<!DOCTYPE html>
<html>
  <head>
    <?=$this->fetch('common/meta.phtml')?>
    <?=$this->fetch('common/styles.phtml')?>
  </head>
  <body>
    <?=$this->fetch('board/menubar.phtml', ['board_id' => $board['id'], 'thread_id' => null])?>
    <?=$this->fetch('common/header.phtml', ['header' => ['title' => "/{$board['id']}/ - {$board['name']}", 'subtitle' => $board['desc']]])?>
    <hr>
    <div class="container-centered">
      <?=$this->fetch('board/postform.phtml', ['board' => $board, 'action' => "/{$board['id']}"])?>
    </div>
    <hr>
    <?php
      foreach ($threads as $thread) {
        echo $this->fetch('board/post_op.phtml', ['context' => 'board', 'board' => $board, 'post' => $thread]);
        echo '<hr>';
      }
    ?>
    <?=$this->fetch('common/pagetable.phtml', ['page' => $page, 'page_n' => $page_n])?>
    <div class="container-centered">
      <?=$this->fetch('common/footer.phtml')?>
    </div>

    <?=$this->fetch('common/scripts.phtml')?>
  </body>
</html>
