<!DOCTYPE html>
<html>
  <head>
    <?=$this->fetch('common/meta.phtml')?>
    <?=$this->fetch('common/styles.phtml')?>
  </head>
  <body>
    <?=$this->fetch('board/menubar.phtml', ['board' => $board])?>
    <?=$this->fetch('common/header.phtml', ['header' => ['title' => "/{$board['id']}/ - {$board['name']}", 'subtitle' => $board['desc']]])?>
    <hr>
    <?=$this->fetch('board/postform.phtml')?>
    <hr>
    <?php
      foreach ($threads as $thread) {
        echo $this->fetch('board/post_op.phtml', ['board' => $board, 'post' => $thread]);
        foreach ($thread['replies'] as $reply) {
          echo $this->fetch('board/post_reply.phtml', ['board' => $board, 'post' => $reply]);
        }
        echo '<hr>';
      }
    ?>
    <?=$this->fetch('common/pagetable.phtml', ['page' => $page, 'page_n' => $page_n])?>
    <?=$this->fetch('common/footer.phtml')?>

    <?=$this->fetch('common/scripts.phtml')?>
  </body>
</html>
