<!DOCTYPE html>
<html>
  <head>
    <?=$this->fetch('common/meta.phtml')?>
    <?=$this->fetch('common/styles.phtml')?>
    <?=$this->fetch('common/scripts.phtml')?>
    <title>/<?=$board['id']?>/ - Catalog</title>
  </head>
  <body>
    <?=$this->fetch('board/menubar.phtml', ['board_id' => $board['id'], 'thread_id' => null])?>
    <?=$this->fetch('common/banner.phtml')?>
    <hr>
    <?=$this->fetch('common/header.phtml', ['h_title' => "/{$board['id']}/ - {$board['name']}", 'h_subtitle' => $board['desc']])?>
    <hr>
    [<a href="../">Return</a>]
    <div class="mode"><span id="mode">Catalog</span></div>
    <div id="form-post-container" class="container-centered">
      <?=$this->fetch('board/postform.phtml', ['context' => 'board', 'board' => $board, 'action' => "/{$board['id']}"])?>
    </div>
    <hr>
    <div id="catalog" class="catalog">
      <?php
        foreach ($threads as $thread) {
          echo $this->fetch('board/post_catalog.phtml', ['board' => $board, 'post' => $thread]);
        }
      ?>
    </div>
    <hr>
    <?=$this->fetch('common/pagetable.phtml', ['page' => $page, 'page_n' => $page_n])?>
    <div class="container-centered">
      <?=$this->fetch('common/footer.phtml')?>
    </div>
  </body>
</html>
