<!DOCTYPE html>
<html>
  <head>
    <?=$this->fetch('common/meta.phtml')?>
    <?=$this->fetch('common/styles.phtml')?>
  </head>
  <body>
    <?=$this->fetch('board/menubar.phtml', ['board_id' => $board])?>
    <?=$this->fetch('common/header.phtml', ['header' => ['title' => "/{$board['id']}/ - {$board['name']}", 'subtitle' => $board['desc']]])?>
    <hr>
    [<a href="../">Return</a>]
    <div class="mode">Catalog</div>
    <?=$this->fetch('board/postform.phtml')?>
    <hr>
    <?php
      foreach ($threads as $thread) {
        echo $this->fetch('board/post_catalog.phtml', ['board_id' => $board, 'post' => $thread]);
      }
    ?>
    <hr>
    <?=$this->fetch('common/pagetable.phtml', ['page' => $page, 'page_n' => $page_n])?>
    <?=$this->fetch('common/footer.phtml')?>

    <?=$this->fetch('common/scripts.phtml')?>
  </body>
</html>
