<!DOCTYPE html>
<html>
  <head>
    <?=$this->fetch('common/meta.phtml')?>
    <?=$this->fetch('common/styles.phtml')?>
    <title>/<?=$board['id']?>/ - Catalog</title>
  </head>
  <body>
    <?=$this->fetch('board/menubar.phtml', ['board_id' => $board['id'], 'thread_id' => null])?>
    <?=$this->fetch('common/banner.phtml')?>
    <hr>
    <?=$this->fetch('common/header.phtml', ['h_title' => "/{$board['id']}/ - {$board['name']}", 'h_subtitle' => $board['desc']])?>
    <hr>
    [<a href="../">Return</a>]
    <div class="mode">Catalog</div>
    <div class="container-centered">
      <?=$this->fetch('board/postform.phtml', ['context' => 'board', 'board' => $board, 'action' => "/{$board['id']}"])?>
    </div>

    <div id="catalog-filter-container"> 
     <input id="catalog-filter" type="text" placeholder="Filter"> 
    </div>
    <br>

    <hr>
    <div id="catalog" class="catalog">
      <?php
        foreach ($threads as $thread) {
          echo $this->fetch('board/post_catalog.phtml', ['board' => $board, 'post' => $thread]);
        }
      ?>
    </div>
    <hr>
    <?=$this->fetch('common/pagetable.phtml', ['page' => $page, 'page_n' => $page_n])?>
    <div class="container-centered">
      <?=$this->fetch('common/footer.phtml')?>
    </div>

    <?=$this->fetch('common/scripts.phtml')?>

    <script>
      // Parempi omana catalog.js tjsp. tiedostona?
      const catalogThreads  = document.querySelectorAll("#catalog .post-catalog");
      const filterInput     = document.querySelector("#catalog-filter");

      filterInput.addEventListener("keyup", (e) => {
          const fitlerStr = e.target.value;
          for (let i = 0; i < catalogThreads.length; i++)
          {
            const t = catalogThreads[i];

            if (t.message == null) t.message = t.querySelector(".post-catalog-message");
            if (t.subject == null) t.subject = t.querySelector(".post-catalog-subject");

            const filterMatch = 
                  t.message?.innerText.includes(fitlerStr) 
              ||  t.subject?.innerText.includes(fitlerStr);

            if (filterMatch) 
              t.classList.remove("hidden");
            else 
              t.classList.add("hidden");
            
          }
        });
    </script>
    
  </body>
</html>

