<!DOCTYPE html>
<html>
  <head>
    <?=$this->fetch('common/meta.phtml')?>
    <?=$this->fetch('common/styles.phtml')?>
    <?=$this->fetch('common/scripts.phtml')?>
    <title><?=$error_type?></title>
  </head>
  <body>
    <?=$this->fetch("{$context}/menubar.phtml", ['board_id' => array_key_first(MB_BOARDS), 'thread_id' => null])?>
    <?=$this->fetch('common/banner.phtml')?>
    <hr>
    <?=$this->fetch('common/header.phtml', ['h_title' => $error_type, 'h_subtitle' => $error_message])?>
    <hr>
    <?php
      if (isset($error_image) && !empty($error_image)) {
        echo "<div class='container-centered'>
          <img src='{$error_image}' width='50%' height='50%'>
        </div>";
      }
    ?>
    <hr>
    <div class="container-centered">
      <?=$this->fetch('common/footer.phtml')?>
    </div>
  </body>
</html>
