<!DOCTYPE html>
<html>
  <head>
    <?=$this->fetch('common/meta.phtml')?>
    <?=$this->fetch('common/styles.phtml')?>
    <title>/<?=$board['id']?>/ - Hidden</title>
  </head>
  <body>
    <?=$this->fetch('board/menubar.phtml', ['board_id' => $board['id'], 'thread_id' => null])?>
    <?=$this->fetch('common/banner.phtml')?>
    <hr>
    <?=$this->fetch('common/header.phtml', ['h_title' => "/{$board['id']}/ - {$board['name']}", 'h_subtitle' => $board['desc']])?>
    <hr>
    [<a href="../">Return</a>]
    <div class="mode">Hidden</div>
    <hr>
    <?=$this->fetch('board/deleteform.phtml', ['context' => 'board', 'board' => $board, 'threads' => $threads])?>
    <?=$this->fetch('common/pagetable.phtml', ['page' => $page, 'page_n' => $page_n])?>
    <div class="container-centered">
      <?=$this->fetch('common/footer.phtml')?>
    </div>

    <?=$this->fetch('common/scripts.phtml')?>
  </body>
</html>
