<!DOCTYPE html>
<html>
  <head>
    <?=$this->fetch('common/meta.phtml')?>
    <?=$this->fetch('common/styles.phtml')?>
    <title>Login</title>
  </head>
  <body>
    <?=$this->fetch('board/menubar.phtml', ['board_id' => array_key_first(MB_BOARDS), 'thread_id' => null])?>
    <?=$this->fetch('common/header.phtml', ['header' => ['title' => 'Manage', 'subtitle' => 'Login']])?>
    <hr>
    <div class="container-centered">
      <?=$this->fetch('manage/loginform.phtml')?>
    </div>
    <hr>
    <div class="container-centered">
      <?=$this->fetch('common/footer.phtml')?>
    </div>

    <?=$this->fetch('common/scripts.phtml')?>
  </body>
</html>
