<!DOCTYPE html>
<html>
  <head>
    <?=$this->fetch('common/meta.phtml')?>
    <?=$this->fetch('common/styles.phtml')?>
    <title>Manage</title>
  </head>
  <body>
    <?=$this->fetch('manage/menubar.phtml', ['board_id' => array_key_first(MB_BOARDS), 'thread_id' => null])?>
    <?=$this->fetch('common/header.phtml', ['header' => ['title' => 'Manage', 'subtitle' => 'Management interface']])?>
    <hr>
    <?php
      switch ($route) {
        case 'accounts':
          if (funcs_common_get_role() !== MB_ROLE_SUPERADMIN) {
            throw new AppException('manage.phtml', 'inline', 'insufficient permissions', SC_FORBIDDEN);
          }

          echo $this->fetch('manage/accounts.phtml', ['account_details' => select_account_details()]);
          break;
        case 'import':
          if (funcs_common_get_role() !== MB_ROLE_SUPERADMIN) {
            throw new AppException('manage.phtml', 'inline', 'insufficient permissions', SC_FORBIDDEN);
          }

          echo $this->fetch('manage/importform.phtml');
          break;
        case 'rebuild':
          if (funcs_common_get_role() !== MB_ROLE_SUPERADMIN) {
            throw new AppException('manage.phtml', 'inline', 'insufficient permissions', SC_FORBIDDEN);
          }

          echo $this->fetch('manage/rebuildform.phtml');
          break;
        default: echo 'Default route'; break;
      }
    ?>
    <hr>
    <div class="container-centered">
      <?=$this->fetch('common/footer.phtml')?>
    </div>

    <?=$this->fetch('common/scripts.phtml')?>
  </body>
</html>
