<!DOCTYPE html>
<html>
  <head>
    <?=$this->fetch('common/meta.phtml')?>
    <?=$this->fetch('common/styles.phtml')?>
    <title><?=$site_name?> - <?=$site_desc?></title>
  </head>
  <body>
    <div class="menubar">
			<div class="boardmenu">
				<?=$this->fetch('common/stylepicker.phtml')?>
			</div>
    </div>
    <?=$this->fetch('common/header.phtml', ['h_title' => "{$site_name}", 'h_subtitle' => '', 'h_logo' => 'logo.png'])?>

    <div class="page-root container-centered" style="margin-top: 32px">
      <div class="box-container">
        <div class="box">
          <div class="box-title">Boards</div>
          <div class="box-content">
            <table>
              <tr style="display: none">
                <th>col1</th>
                <th>col2</th>
                <th>col3</th>
                <th>col4</th>
              </tr>
              <?php
                $board_table_n = 0;
                foreach (MB_BOARDS as $key => $board) {
                  if ($board_table_n % 4 === 0) {
                    echo '<tr>';
                  }

                  echo "<td><a href='/{$board['id']}/'>{$board['name']}</a></td>";

                  if ($board_table_n % 4 === 3) {
                    echo '</tr>';
                  }

                  $board_table_n++;
                }
                if ($board_table_n % 4 !== 0) {
                  echo '</tr>';
                }
              ?>
            </table>
          </div>
        </div>
      </div>
      <div class="box-container">
        <div class="box">
          <div class="box-title">Stats</div>
          <div class="box-content">
            <table>
              <tr style="display: none">
                <th>col1</th>
                <th>col2</th>
                <th>col3</th>
              </tr>
              <tr>
                <?php
                  $total_posts = number_format($site_stats['total_posts'], 0, '.', ',');
                  $current_posts = number_format($site_stats['current_posts'], 0, '.', ',');
                  $unique_posters = number_format($site_stats['unique_posters'], 0, '.', ',');

                  echo "<td><strong>Total Posts: </strong>{$total_posts}</td>";
                  echo "<td><strong>Current Posts: </strong>{$current_posts}</td>";
                  echo "<td><strong>Unique Posters: </strong>{$unique_posters}</td>";
                ?>
              </tr>
              <tr>
                <?php
                  $imported_posts = number_format($site_stats['imported_posts'], 0, '.', ',');
                  $current_files = number_format($site_stats['current_files'], 0, '.', ',');
                  $active_content = funcs_common_human_filesize($site_stats['active_content']);

                  echo "<td><strong>Imported Posts: </strong>{$imported_posts}</td>";
                  echo "<td><strong>Current Files: </strong>{$current_files}</td>";
                  echo "<td><strong>Active Content: </strong>{$active_content}</td>";
                ?>
              </tr>
            </table>
          </div>
        </div>
      </div>
      <div class="box-container">
        <div class="box">
          <div class="box-title">Rules</div>
          <div class="box-content">
            <?=MB_SITE_RULES?>
          </div>
        </div>
      </div>
    </div>

    <hr>
    <div class="container-centered">
      <?=$this->fetch('common/footer.phtml')?>
    </div>

    <?=$this->fetch('common/scripts.phtml')?>
  </body>
</html>
