<!DOCTYPE html>
<html>
  <head>
    <?=$this->fetch('common/meta.phtml')?>
    <?=$this->fetch('common/styles.phtml')?>
    <?=$this->fetch('common/scripts.phtml')?>
    <?php
      $title = "/{$board['id']}/ - ";
      if (strlen($thread['subject']) > 0) {
        $title .= $thread['subject'];
      } else {
        // TODO: create specific function for this
        $title .= substr(trim(str_ireplace("\n", '', strip_tags($thread['message_rendered']))), 0, 75);
      }
      echo "<title>{$title}</title>";
    ?>
  </head>
  <body>
    <?=$this->fetch('board/menubar.phtml', ['board_id' => $board['id'], 'thread_id' => $thread['post_id']])?>
    <?=$this->fetch('common/banner.phtml')?>
    <hr>
    <?=$this->fetch('common/header.phtml', ['h_title' => "/{$board['id']}/ - {$board['name']}", 'h_subtitle' => $board['desc']])?>
    <hr>
    <div class="mode">Posting mode: <span id="mode">Reply</span></div>
    <div id="form-post-container" class="container-centered">
      <?=$this->fetch('board/postform.phtml', ['context' => 'thread', 'board' => $board, 'action' => "/{$board['id']}/{$thread['post_id']}"])?>
    </div>
    <hr>
    <div id="navlinks-top" class="navlinks">
      [<a id="navlinks-top-index" href="/<?=$board['id']?>/">Return</a>]
      [<a id="navlinks-top-catalog" href="/<?=$board['id']?>/catalog/">Catalog</a>]
      [<a id="navlinks-top-bottom" href="#bottom">Bottom</a>]
    </div>
    <hr>
    <?=$this->fetch('board/deleteform.phtml', ['context' => 'thread', 'board' => $board, 'threads' => [$thread]])?>
    <div id="navlinks-bottom" class="navlinks">
      [<a id="navlinks-bottom-index" href="/<?=$board['id']?>/">Return</a>]
      [<a id="navlinks-bottom-catalog" href="/<?=$board['id']?>/catalog/">Catalog</a>]
      [<a id="navlinks-bottom-top" href="#top">Top</a>]
    </div>
    <div id="bottom"></div>
    <div class="container-centered">
      <?=$this->fetch('common/footer.phtml')?>
    </div>
  </body>
</html>
