<!DOCTYPE html>
<html>
  <head>
    <?=$this->fetch('common/meta.phtml')?>
    <?=$this->fetch('common/styles.phtml')?>
  </head>
  <body>
    <?=$this->fetch('board/menubar.phtml', ['board_id' => $board])?>
    <?=$this->fetch('common/header.phtml', ['header' => ['title' => "/{$board['id']}/ - {$board['name']}", 'subtitle' => $board['desc']]])?>
    <hr>
    [<a href="../">Return</a>]
    <div class="mode">Posting mode: Reply</div>
    <div class="container-centered">
      <?=$this->fetch('board/postform.phtml')?>
    </div>
    <hr>
    <?php
      $thread['message_truncated'] = null;
      echo $this->fetch('board/post_op.phtml', ['board_id' => $board, 'post' => $thread]);
      foreach ($replies as $reply) {
        $reply['message_truncated'] = null;
        echo $this->fetch('board/post_reply.phtml', ['board_id' => $board, 'post' => $reply]);
      }
    ?>
    <hr>
    [<a href="../">Return</a>]
    <div class="container-centered">
      <?=$this->fetch('common/footer.phtml')?>
    </div>

    <?=$this->fetch('common/scripts.phtml')?>
  </body>
</html>
