<div class="menubar">
  <div class="boardlist">
    [<?php
      foreach (MB_BOARDS as $key => $board_cfg) {
        echo "<a href='/{$board_cfg['id']}/'>{$board_cfg['id']}</a>";
        if ($key !== array_key_last(MB_BOARDS)) {
          echo ' / ';
        }
      }
    ?>]
  </div>
  <div class="boardmenu">
    [<a href="/">Home</a>]
    [<a href="/<?=$board_id?>/hidden/">Hidden</a>]
    [<a href="/<?=$board_id?>/catalog/">Catalog</a>]
    [<a href="/manage/">Manage</a>]
    <?=$this->fetch('common/stylepicker.phtml')?>
  </div>
</div>
