<div id="<?= $post['id'] ?>" class="catalog__single">
  <div class="catalog__single__file-thumb">
    <a href="/<?=$post['board']?>/<?=$post['id']?>">
      <img id="thumb-<?= $post['id'] ?>" src="/src/<?= $post['thumb'] ?>" loading="lazy">
    </a>
  </div>
  <div class="catalog__single__reply-count"><?= $post['reply_count'] ?></div>
  <div class="catalog__single__message"><?= truncate_message(message: $post['message'], length: 72) ?></div>
</div>
