<div class="thread post-catalog" id="thread_<?=$post['board_id']?>-<?=$post['post_id']?>">
  <?php
    $thumb_src = null;
    $thumb_width = null;
    $thumb_height = null;
    if ($post['file_rendered'] !== '') {
      $thumb_src = "{$post['thumb']}";
      $thumb_width = $post['thumb_width'] * 0.6;
      $thumb_height = $post['thumb_height'] * 0.6;
    } else {
      $thumb_src = '/static/nofile.png';
      $thumb_width = 200 * 0.6;
      $thumb_height = 200 * 0.6;
    }
    echo "
      <a href='/{$post['board_id']}/{$post['post_id']}'>
        <img id='thumb-{$post['board_id']}-{$post['post_id']}' src='{$thumb_src}' width='{$thumb_width}' height='{$thumb_height}' loading='lazy'>
      </a>
    ";

    $stickied = '';
    if ($post['stickied'] === 1) {
      $stickied = "<img src='/static/sticky.png' alt='Stickied' title='Stickied' width='16' height='16'>";
    }
    $locked = '';
    if ($post['locked'] === 1) {
      $locked = "<img src='/static/lock.png' alt='Locked' title='Locked' width='16' height='16'>";
    }

    // TODO: create specific function for this
    $message_truncated = substr(trim(str_ireplace("\n", '', strip_tags($post['message_rendered']))), 0, 75);
    echo "
      <div class='post-catalog-meta'>{$stickied}{$locked} R: <b>{$post['reply_count']}</b></div>
      <div class='post-catalog-title'>
        <span class='post-catalog-subject'>{$post['subject']}</span>
        <span class='post-catalog-message'>{$message_truncated}</span>
      </div>
    "
  ?>
</div>
