<?php
  if (isset($post['file']) && !empty($post['file'])) {
    $thumb_src = "{$post['thumb']}";
    $thumb_width = $post['thumb_width'];
    $thumb_height = $post['thumb_height'];
    if (isset($post['spoiler']) && $post['spoiler'] == true) {
      $thumb_src = '/static/spoiler.png';
      $thumb_width = 250;
      $thumb_height = 250;
    }
    $img_id = $context !== 'preview' ? "id='thumb-{$post['board_id']}-{$post['post_id']}'" : '';


    if ($post['embed'] === 0) {
      echo "
        <div class='file-info'>
          File: <a href='{$post['file']}' target='_blank'>{$post['file']}</a>
          -
          ({$post['file_size_formatted']}, {$post['image_width']}x{$post['image_height']}, {$post['file_original']})
        </div>
        <div class='file-thumb'>
          <a class='file-thumb-href' href='{$post['file']}' target='_blank'>
            <img {$img_id} src='{$thumb_src}' width='{$thumb_width}' height='{$thumb_height}' loading='lazy'>
          </a>
        </div>
      ";
    } else {
      echo "
        <div class='file-info'>
          Embed: <a href='{$post['file_hex']}' target='_blank'>{$post['file_original']}</a>
          -
          ({$post['image_width']}x{$post['image_height']}, Embedded URL)
        </div>
        <div class='file-thumb'>
          <a class='file-thumb-href' href='{$post['file']}' target='_blank'>
            <img {$img_id} src='{$thumb_src}' width='{$thumb_width}' height='{$thumb_height}' loading='lazy'>
          </a>
        </div>
        <div class='file-data' style='display:none;'>{$post['file']}</div>
      ";
    }
  }
?>
