<form id="postform" class="postform" method="post" enctype="multipart/form-data">
  <div class="postform-group">
    <label for="name">Name</label>
    <input type="text" name="name" autocomplete="off">
  </div>
  <div class="postform-group">
    <label for="email">E-mail</label>
    <input type="text" name="email" autocomplete="off">
  </div>
  <div class="postform-group">
    <label for="subject">Subject</label>
    <input type="text" name="subject" autocomplete="off">
    <input type="submit" value="Submit">
  </div>
  <div class="postform-group">
    <label for="message">Message</label>
    <textarea name="message" autocomplete="off" cols="48" rows="4" maxlength="8192"></textarea>
  </div>
  <div class="postform-group">
    <label for="file">File</label>
    <input type="file" name="file" autocomplete="off" size="35">
    <input type="checkbox" name="spoiler" value="1">
    Spoiler
    <input type="checkbox" name="anonfile" value="1">
    No filename
  </div>
  <div class="postform-group">
    <label for="embed">Embed</label>
    <input type="text" name="embed" autocomplete="off">
    (paste a YouTube URL)
  </div>
  <div class="postform-group">
    <label for="password">Password</label>
    <input type="password" name="password">
    (for post and file deletion)
  </div>
</form>
