<div class="post reply">
  <div class="post-dash">¨</div>
    <div class="reply" id="<?=$post['id']?>">
      <div class="post-info">
        <label>
          <input type="checkbox">
          <span class="post-subject"><?=$post['subject']?></span>
          <span class="post-name"><?=$post['name']?></span>
          <span class="post-datetime"><?=@strftime(MB_GLOBAL['datefmt'], $post['timestamp'])?></span>
        </label>
        <span class="post-id">
          <a href="/<?=$post['board']?>/<?=$post['parent']?>/#<?=$post['id']?>">No.</a><a href="/<?=$post['board']?>/<?=$post['parent']?>/#q<?=$post['id']?>"><?=$post['id']?></a>
        </span>
      </div>
      <?php
        if ($post['file'] !== '') {
          echo "
            <div class='file-info'>
              <a href='/src/{$post['file']}'>{$post['file']}</a>
              -
              ({$post['file_size_formatted']}, {$post['image_width']}x{$post['image_height']}, {$post['file_original']})
            </div>
            <div class='file-thumb'>
              <a href='/src/{$post['file']}' target='_blank'>
                <img id='thumb-{$post['id']}' src='/src/{$post['thumb']}' loading='lazy'>
              </a>
            </div>
          ";
        }
      ?>
      <div class="post-message-wrapper">
        <div class="post-message">
          <?php
            if (!isset($post['message_truncated'])) {
              echo $post['message_rendered'];
            } else {
              echo $post['message_truncated'];
              echo '<br><span class="truncated">Post truncated. Click reply to view.</span><br>';
            }
          ?>
        </div>
      </div>
  </div>
</div>
