<form id="postform" class="postform" method="post" action="<?=$action?>" enctype="multipart/form-data">
  <div class="postform-group">
    <label for="name">Name</label>
    <input type="text" name="name">
  </div>
  <div class="postform-group">
    <label for="email">E-mail</label>
    <input type="text" name="email">
  </div>
  <div class="postform-group">
    <label for="subject">Subject</label>
    <input type="text" name="subject" autocomplete="off">
    <input type="submit" value="Submit">
  </div>
  <div class="postform-group">
    <label class="postform-message-label" for="message">Message</label>
    <textarea id="postform-message" name="message" autocomplete="off" cols="48" rows="4" maxlength="8192"></textarea>
  </div>
  <div class="postform-group">
    <?php
      if ($context === 'board' && MB_GLOBAL['captcha_thread'] || $context === 'thread' && MB_GLOBAL['captcha_reply']) {
        $label = "<label class='postform-captcha-label' for='captcha'>Captcha</label>\n";
        $captcha = '<div class="h-captcha" data-sitekey="' . MB_GLOBAL['hcaptcha_site'] . '"></div>';
        echo $label . $captcha;
      }
    ?>
  </div>
  <div class="postform-group">
    <?php
      if ($board['type'] === 'main') {
        $label = "<label for='board'>Board</label>\n";
        $select_input = '<select id="board" name="board">';
        $select_options = '<option value=""></option>';
        foreach (MB_BOARDS as $key => $val) {
          if ($val['type'] === 'main') {
            continue;
          }
          
          $select_options .= "<option value='{$key}'>/{$key}/ - {$val['name']}</option>";
        }
        echo $label . $select_input . $select_options . '</select>';
      }
    ?>
  </div>
  <div class="postform-group">
    <label for="file">File</label>
    <input type="file" name="file" autocomplete="off" size="35">
    <input type="checkbox" name="spoiler" value="1">
    Spoiler
    <input type="checkbox" name="anonfile" value="1">
    No filename
  </div>
  <div class="postform-group">
    <label for="embed">Embed</label>
    <input type="text" name="embed" autocomplete="off">
    (paste a YouTube URL)
  </div>
  <div class="postform-group">
    <label for="password">Password</label>
    <input id="postform-password" type="password" name="password">
    (for post and file deletion)
  </div>
</form>
