<div class="post-catalog" id="<?=$post['board_id']?>-<?=$post['post_id']?>">
  <?php
    if ($post['file'] !== '') {
      $thumb_src = "{$post['thumb']}";
      $thumb_width = $post['thumb_width'] * 0.6;
      $thumb_height = $post['thumb_height'] * 0.6;
      if (isset($post['spoiler']) && $post['spoiler'] == true) {
        $thumb_src = '/static/spoiler.png';
        $thumb_width = 150;
        $thumb_height = 150;
      }

      echo "
        <a href='/{$post['board_id']}/{$post['post_id']}'>
          <img id='thumb-{$post['board_id']}-{$post['post_id']}' src='{$thumb_src}' width='{$thumb_width}' height='{$thumb_height}' loading='lazy'>
        </a>
      ";
    }

    // TODO: create specific function for this
    $message_truncated = substr(trim(str_ireplace("\n", '', strip_tags($post['message_rendered']))), 0, 75);
    echo "
      <div class='post-catalog-meta'>R: <b>{$post['reply_count']}</b></div>
      <div class='post-catalog-title'>
        <span class='post-catalog-subject'>{$post['subject']}</span>
        <span class='post-catalog-message'>{$message_truncated}</span>
      </div>
    "
  ?>
</div>
