<?php
  if (isset($post['file']) && strlen($post['file']) > 0) {
    $thumb_src = "/src/{$post['thumb']}";
    $thumb_width = $post['thumb_width'];
    $thumb_height = $post['thumb_height'];
    if (isset($post['spoiler']) && $post['spoiler'] == true) {
      $thumb_src = '/static/spoiler.png';
      $thumb_width = 250;
      $thumb_height = 250;
    }
    $img_id = $context !== 'preview' ? "id='thumb-{$post['board_id']}-{$post['post_id']}'" : '';

    echo "
      <div class='file-info'>
        File: <a href='/src/{$post['file']}'>{$post['file']}</a>
        -
        ({$post['file_size_formatted']}, {$post['image_width']}x{$post['image_height']}, {$post['file_original']})
      </div>
      <div class='file-thumb'>
        <a class='file-thumb-href' href='/src/{$post['file']}' target='_blank'>
          <img {$img_id} src='{$thumb_src}' width='{$thumb_width}' height='{$thumb_height}' loading='lazy'>
        </a>
      </div>
    ";
  }
?>
