<div class="post reply" style="margin-bottom: 0px">
  <div class="reply">
    <div class="post-info">
      <label>
        <input type="checkbox">
        <span class="post-subject"><?=$post['subject']?></span>
        <?php
          if (isset($post['email']) && strlen($post['email']) > 0) {
            echo "<a href='mailto:{$post['email']}'><span class='post-name'>{$post['name']}</span></a>";
          } else {
            echo "<span class='post-name'>{$post['name']}</span>";
          }
        ?>
        <span class="post-datetime"><?=@strftime(MB_GLOBAL['datefmt'], $post['timestamp'])?></span>
      </label>
      <span class="post-id">
        <a href="/<?=$post['board_id']?>/<?=$post['parent_id']?>/#<?=$post['id']?>">No.</a><a href="/<?=$post['board_id']?>/<?=$post['parent_id']?>/#q<?=$post['id']?>"><?=$post['id']?></a>
      </span>
    </div>
    <?php
      if ($post['file'] !== '') {
        $thumb_src = "/src/{$post['thumb']}";
        if (isset($post['spoiler']) && $post['spoiler'] == true) {
          $thumb_src = '/static/spoiler.png';
        }
  
        echo "
          <div class='file-info'>
            <a href='/src/{$post['file']}'>{$post['file']}</a>
            -
            ({$post['file_size_formatted']}, {$post['image_width']}x{$post['image_height']}, {$post['file_original']})
          </div>
          <div class='file-thumb'>
            <a href='/src/{$post['file']}' target='_blank'>
              <img src='{$thumb_src}' loading='lazy'>
            </a>
          </div>
        ";
      }
    ?>
    <div class="post-message-wrapper">
      <div class="post-message">
        <?php
          if (!isset($post['message_truncated'])) {
            echo $post['message_rendered'];
          } else {
            echo $post['message_truncated'];
            echo '<br><span class="truncated">Post truncated. Click reply to view.</span><br>';
          }
        ?>
      </div>
    </div>
  </div>
</div>
