<div class="post">
  <?php
    if ($post['file'] !== '') {
      $thumb_src = "/src/{$post['thumb']}";
      $thumb_width = $post['thumb_width'];
      $thumb_height = $post['thumb_height'];
      if (isset($post['spoiler']) && $post['spoiler'] == true) {
        $thumb_src = '/static/spoiler.png';
        $thumb_width = 250;
        $thumb_height = 250;
      }

      echo "
        <div class='file-info'>
          File: <a href='/src/{$post['file']}'>{$post['file']}</a>
          -
          ({$post['file_size_formatted']}, {$post['image_width']}x{$post['image_height']}, {$post['file_original']})
        </div>
        <div class='file-thumb'>
          <a href='/src/{$post['file']}' target='_blank'>
            <img src='{$thumb_src}' width='{$thumb_width}' height='{$thumb_height}' loading='lazy'>
          </a>
        </div>
      ";
    }
  ?>
  <div class="post-info">
    <label>
      <input type="checkbox">
      <span class="post-subject"><?=$post['subject']?></span>
      <?=$post['nameblock']?>
    </label>
    <span class="post-id">
      <a href="/<?=$post['board_id']?>/<?=$post['post_id']?>/#<?=$post['board_id']?>-<?=$post['post_id']?>">No.</a><a href="/<?=$post['board_id']?>/<?=$post['post_id']?>/#q<?=$post['post_id']?>"><?=$post['post_id']?></a>
    </span>
  </div>
  <div class="post-message-wrapper">
    <div class="post-message">
      <?php
        if (!isset($post['message_truncated'])) {
          echo $post['message_rendered'];
        } else {
          echo $post['message_truncated'];
          echo '<br><br><span class="truncated">Post truncated. Click reply to view.</span><br>';
        }
      ?>
    </div>
  </div>
  <?php
    foreach ($post['replies'] as $reply) {
      if ($context === 'thread') {
        $reply['message_truncated'] = null;
      }
      echo $this->fetch('board/post_reply.phtml', ['context' => $context, 'post' => $reply]);
    }
  ?>
</div>
