<div class="post">
  <?=$this->fetch('board/post_file.phtml', ['context' => 'preview', 'post' => $post])?>
  <div class="post-info">
    <label>
      <input type="checkbox" disabled>
      <span class="post-subject"><?=$post['subject']?></span>
      <?=$post['nameblock']?>
    </label>
    <span class="post-id">
      <a href="/<?=$post['board_id']?>/<?=$post['post_id']?>/#<?=$post['board_id']?>-<?=$post['post_id']?>">No.</a><a href="/<?=$post['board_id']?>/<?=$post['post_id']?>/#q<?=$post['post_id']?>"><?=$post['post_id']?></a>
    </span>
  </div>
  <div class="post-message-wrapper">
    <div class="post-message">
      <?php
        if (!isset($post['message_truncated'])) {
          echo $post['message_rendered'];
        } else {
          echo $post['message_truncated'];
          echo '<br><br><span class="truncated">Post truncated. Click reply to view.</span><br>';
        }
      ?>
    </div>
  </div>
  <?php
    foreach ($post['replies'] as $reply) {
      if ($context === 'thread') {
        $reply['message_truncated'] = null;
      }
      echo $this->fetch('board/post_reply.phtml', ['context' => $context, 'post' => $reply]);
    }
  ?>
</div>
