<div class="post" id="<?=$post['id']?>">
  <?php
    if ($post['file'] !== '') {
      $thumb_src = "/src/{$post['thumb']}";
      $thumb_width = $post['thumb_width'];
      $thumb_height = $post['thumb_height'];
      if (isset($post['spoiler']) && $post['spoiler'] == true) {
        $thumb_src = '/static/spoiler.png';
        $thumb_width = 250;
        $thumb_height = 250;
      }

      echo "
        <div class='file-info'>
          File: <a href='/src/{$post['file']}'>{$post['file']}</a>
          -
          ({$post['file_size_formatted']}, {$post['image_width']}x{$post['image_height']}, {$post['file_original']})
        </div>
        <div class='file-thumb'>
          <a href='/src/{$post['file']}' target='_blank'>
            <img id='thumb-{$post['id']}' src='{$thumb_src}' width='{$thumb_width}' height='{$thumb_height}' loading='lazy'>
          </a>
        </div>
      ";
    }
  ?>
  <div class="post-info">
    <label>
      <input type="checkbox" name="delete[]" value="<?=$post['board_id']?>/<?=$post['id']?>">
      <?php
        if ($board['type'] === 'main') {
          echo "<span class='post-board'>/{$post['board_id']}/</span>";
        }
      ?>
      <span class="post-subject"><?=$post['subject']?></span>
      <?php
        if (isset($post['email']) && strlen($post['email']) > 0) {
          echo "<a href='mailto:{$post['email']}'><span class='post-name'>{$post['name']}</span></a>";
        } else {
          echo "<span class='post-name'>{$post['name']}</span>";
        }
      ?>
      <span class="post-datetime"><?=@strftime(MB_GLOBAL['datefmt'], $post['timestamp'])?></span>
    </label>
    <span class="post-id">
      <a href="/<?=$post['board_id']?>/<?=$post['id']?>/#<?=$post['id']?>">No.</a><a href="/<?=$post['board_id']?>/<?=$post['id']?>/#q<?=$post['id']?>"><?=$post['id']?></a>
    </span>
    [<a href="/<?=$post['board_id']?>/<?=$post['id']?>/">Reply</a>]
    <a href="#" class="dd-menu-btn" data-board_id="<?=$post['board_id']?>" data-id="<?=$post['id']?>" data-cmd="post-menu">▶</a>
  </div>
  <div class="post-message-wrapper">
    <div class="post-message">
      <?php
        if ($context === 'thread' || !isset($post['message_truncated'])) {
          echo $post['message_rendered'];
        } else {
          echo $post['message_truncated'];
        }
      ?>
    </div>
    <?php
      $truncated = false;
      if ($context === 'board' && isset($post['message_truncated'])) {
        $truncated = true;
        echo '<span class="truncated">Post truncated. Click reply to view.</span>';
      }

      if ($context === 'board') {
        $replies_omitted = $post['replies_n'] - count($post['replies']);
        if ($replies_omitted > 0) {
          echo ($truncated ? '<br>' : '') . "<span class='omitted'>{$replies_omitted} posts omitted. Click reply to view.</span>";
        }
      }
    ?>
  </div>
  <?php
    foreach ($post['replies'] as $reply) {
      echo $this->fetch('board/post_reply.phtml', ['context' => $context, 'post' => $reply]);
    }
  ?>
</div>
