<div class="post" id="<?=$post['id']?>">
  <div class="file-info">
    File: <a href="/src/<?=$post['file']?>"><?=$post['file']?></a>
    -
    (<?=$post['file_size_formatted']?>, <?=$post['image_width']?>x<?=$post['image_height']?>, <?=$post['file_original']?>)
  </div>
  <div class="file-thumb">
    <a href="/src/<?=$post['file']?>" target="_blank">
      <img id="thumb-<?=$post['id']?>" src="/src/<?=$post['file']?>">
    </a>
  </div>
  <div class="post-info">
    <label>
      <input type="checkbox">
      <span class="post-subject"><?=$post['subject']?></span>
      <span class="post-name"><?=$post['name']?></span>
      <span class="post-datetime"><?=@strftime(MB_GLOBAL['datefmt'], $post['timestamp'])?></span>
    </label>
    <span class="post-id">
      <a href="/<?=$post['board']?>/<?=$post['id']?>/#<?=$post['id']?>">No.</a><a href="/<?=$post['board']?>/<?=$post['id']?>/#q<?=$post['id']?>"><?=$post['id']?></a>
    </span>
    [<a href="<?=$post['id']?>/">Reply</a>]
  </div>
  <div class="post-message-wrapper">
    <div class="post-message">
      <?=$post['message']?>
    </div>
  </div>
</div>
