<form id="reportform" class="reportform" method="post">
  <p>Reporting post <strong><?=$post['id']?></strong> on board <strong>/<?=$post['board_id']?>/</strong>.</p>
  <fieldset id="reportform-type">
    <legend>Report type</legend>
    <?php
      $select_input = '<select id="type" name="type">';
      $select_options = '<option value=""></option>';
      foreach (MB_GLOBAL['report_types'] as $key => $val) {
        $select_options .= "<option value='{$key}'>{$val}</option>";
      }
      echo $select_input . $select_options . '</select>';
    ?>
  </fieldset>
  <p>Submitting <strong>false</strong> or <strong>misclassified</strong> reports will result in a ban.</p>
  <button type="submit">Submit</button>
</form>
