FROM node:18-alpine AS build

COPY . /app

WORKDIR /app

RUN yarn && npx gulp build

FROM nginx:1.23.2-alpine

COPY docker/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf
RUN chmod 644 /etc/nginx/conf.d/default.conf

COPY --from=build /app/public /app/public
