<!DOCTYPE html>
<html>
  <head>
    <?=$this->render(__ROOT__ . '/common/templates/meta.phtml')?>
    <?=$this->render(__ROOT__ . '/common/templates/styles.phtml')?>
    <?=$this->render(__ROOT__ . '/common/templates/scripts.phtml')?>
    <title>Logs</title>
  </head>
  <body>
    <div id="menubar" class="menubar">
			<div id="boardmenu" class="boardmenu">
        <?=$this->render(__ROOT__ . '/common/templates/modmenu.phtml')?>
			</div>
    </div>
    <?=$this->render(__ROOT__ . '/common/templates/header.phtml', ['h_title' => 'Logs', 'h_subtitle' => 'Public list of latest logs'])?>

    <div class="page-root container-centered">
      <div class="box-container">
        <div class="box">
          <div class="box-title">Logs (last 2 weeks)</div>
          <div class="box-content">
            <table>
              <thead>
                <tr>
                  <th>id</th>
                  <th>timestamp</th>
                  <th>message</th>
                </tr>
              </thead>
              <tbody>
                <?php
                  foreach ($logs as $log) {
                    echo "
                      <tr>
                        <td>{$log->id}</td>
                        <td>{$log->fmt_timestamp()}</td>
                        <td>{$log->fmt_message(32)}</td>
                      </tr>
                    ";
                  }
                ?>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
    <hr>
    <div class="container-centered">
      <?=$this->render(__ROOT__ . '/common/templates/footer.phtml')?>
    </div>
  </body>
</html>
