<!DOCTYPE html>
<html>
  <head>
    <?=$this->render(__ROOT__ . '/common/templates/meta.phtml')?>
    <?=$this->render(__ROOT__ . '/common/templates/styles.phtml')?>
    <?=$this->render(__ROOT__ . '/common/templates/scripts.phtml')?>
    <title>/<?=$board['id']?>/ - <?=__('nav.catalog')?></title>
  </head>
  <body>
    <?=$this->render(__DIR__ . '/components/menubar.phtml', ['board_id' => $board['id'], 'thread_id' => null])?>
    <?=$this->render(__ROOT__ . '/common/templates/banner.phtml')?>
    <hr>
    <?=$this->render(__ROOT__ . '/common/templates/header.phtml', ['h_title' => "/{$board['id']}/ - {$board['name']}", 'h_subtitle' => $board['desc']])?>
    <hr>
    <?php if ($board['type'] === 'main') { ?>
      <?=$this->render(__DIR__ . '/components/board_filter.phtml', ['board' => $board, 'board_filters' => $board_filters])?>
      <hr>
    <?php } ?>
    <div class="mode"><span id="mode" data-mode="catalog"><?=__('nav.catalog')?></span></div>
    <div id="form-post-container" class="container-centered">
      <?=$this->render(__DIR__ . '/components/postform.phtml', ['context' => 'board', 'board' => $board, 'action' => "/{$board['id']}"])?>
    </div>
    <hr>
    <div id="navlinks-top" class="navlinks">
      [<a id="navlinks-top-index" href="/<?=$board['id']?>/"><?=__('nav.return')?></a>]
      [<a id="navlinks-top-refresh" href="./"><?=__('nav.refresh')?></a>]
    </div>
    <hr>
    <div id="catalog" class="catalog">
      <?php
        foreach ($threads as $thread) {
          echo $this->render(__DIR__ . '/components/post_catalog.phtml', ['board' => $board, 'post' => $thread]);
        }
      ?>
    </div>
    <hr>
    <?=$this->render(__ROOT__ . '/common/templates/pagetable.phtml', ['page' => $page, 'page_n' => $page_n])?>
    <div class="container-centered">
      <?=$this->render(__ROOT__ . '/common/templates/footer.phtml')?>
    </div>
  </body>
</html>
