<!DOCTYPE html>
<html>
  <head>
    <?=$this->render(__ROOT__ . '/common/templates/meta.phtml')?>
    <?=$this->render(__ROOT__ . '/common/templates/styles.phtml')?>
    <?=$this->render(__ROOT__ . '/common/templates/scripts.phtml')?>
    <title>/<?=$board['id']?>/ - Report</title>
  </head>
  <body>
    <div class="container-centered">
      <?=$this->render(__DIR__ . '/components/reportform.phtml', ['post' => $post])?>
    </div>
    <hr>
    <div class="container-centered">
    <?=$this->render(__ROOT__ . '/common/templates/footer.phtml')?>
    </div>
  </body>
</html>
