<!DOCTYPE html>
<html>
  <head>
    <?=$this->render(__ROOT__ . '/common/templates/meta.phtml')?>
    <?=$this->render(__ROOT__ . '/common/templates/styles.phtml')?>
    <?=$this->render(__ROOT__ . '/common/templates/scripts.phtml', ['hcaptcha' => MB_CAPTCHA_REPLY])?>
    <?php
      $title = "/{$board['id']}/ - ";
      if (isset($thread['subject']) && strlen($thread['subject']) > 0) {
        $title .= $thread['subject'];
      } else {
        // TODO: create specific function for this
        $title .= substr(trim(str_ireplace("\n", '', strip_tags($thread['message_rendered']))), 0, 75);
      }
      echo "<title>{$title}</title>";
    ?>
  </head>
  <body>
    <?=$this->render(__DIR__ . '/components/menubar.phtml', ['board_id' => $board['id'], 'thread_id' => $thread['post_id']])?>
    <?=$this->render(__ROOT__ . '/common/templates/banner.phtml')?>
    <hr>
    <?=$this->render(__ROOT__ . '/common/templates/header.phtml', ['h_title' => "/{$board['id']}/ - {$board['name']}", 'h_subtitle' => $board['desc']])?>
    <hr>
    <div class="mode"><?=__('post.posting_mode')?> <span id="mode" data-mode="reply"><?=__('post.reply')?></span></div>
    <div id="form-post-container" class="container-centered">
      <?=$this->render(__DIR__ . '/components/postform.phtml', ['context' => 'thread', 'board' => $board, 'action' => "/{$board['id']}/{$thread['post_id']}"])?>
    </div>
    <hr>
    <div id="navlinks-top" class="navlinks">
      [<a id="navlinks-top-index" href="/<?=$board['id']?>/"><?=__('nav.return')?></a>]
      [<a id="navlinks-top-catalog" href="/<?=$board['id']?>/catalog/"><?=__('nav.catalog')?></a>]
      [<a id="navlinks-top-bottom" href="#bottom"><?=__('nav.bottom')?></a>]
    </div>
    <hr>
    <?=$this->render(__DIR__ . '/components/deleteform.phtml', ['context' => 'thread', 'board' => $board, 'threads' => [$thread]])?>
    <div id="navlinks-bottom" class="navlinks">
      [<a id="navlinks-bottom-index" href="/<?=$board['id']?>/"><?=__('nav.return')?></a>]
      [<a id="navlinks-bottom-catalog" href="/<?=$board['id']?>/catalog/"><?=__('nav.catalog')?></a>]
      [<a id="navlinks-bottom-top" href="#top"><?=__('nav.top')?></a>]
    </div>
    <div id="bottom"></div>
    <div class="container-centered">
    <?=$this->render(__ROOT__ . '/common/templates/footer.phtml')?>
    </div>
  </body>
</html>
