<!DOCTYPE html>
<html>
  <head>
    <?=$this->render(__ROOT__ . '/common/templates/meta.phtml')?>
    <?=$this->render(__ROOT__ . '/common/templates/styles.phtml')?>
    <?=$this->render(__ROOT__ . '/common/templates/scripts.phtml')?>
    <title><?=__('bans.title')?></title>
  </head>
  <body>
    <div id="menubar" class="menubar">
			<div id="boardmenu" class="boardmenu">
        <?=$this->render(__ROOT__ . '/common/templates/modmenu.phtml')?>
			</div>
    </div>
    <?=$this->render(__ROOT__ . '/common/templates/header.phtml', ['h_title' => __('bans.title'), 'h_subtitle' => __('bans.subtitle')])?>

    <div class="page-root container-centered">
      <div class="box-container">
        <div class="box">
          <div class="box-title"><?=__('bans.heading')?></div>
          <div class="box-content">
            <table>
              <thead>
                <tr>
                  <th><?=__('manage.th.id')?></th>
                  <th><?=__('manage.th.ip')?></th>
                  <th><?=__('manage.th.timestamp')?></th>
                  <th><?=__('manage.th.expire')?></th>
                  <th><?=__('manage.th.reason')?></th>
                </tr>
              </thead>
              <tbody>
                <?php
                  foreach ($bans as $ban) {
                    echo "
                      <tr>
                        <td>{$ban->id}</td>
                        <td>{$ban->redact_ip()}</td>
                        <td>{$ban->fmt_timestamp()}</td>
                        <td>{$ban->fmt_expire()}</td>
                        <td>{$ban->fmt_reason(16)}</td>
                      </tr>
                    ";
                  }
                ?>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
    <hr>
    <div class="container-centered">
      <?=$this->render(__ROOT__ . '/common/templates/footer.phtml')?>
    </div>
  </body>
</html>
