<!DOCTYPE html>
<html>
  <head>
    <?=$this->render(__ROOT__ . '/common/templates/meta.phtml')?>
    <?=$this->render(__ROOT__ . '/common/templates/styles.phtml')?>
    <?=$this->render(__ROOT__ . '/common/templates/scripts.phtml')?>
    <title>Bans</title>
  </head>
  <body>
    <div id="menubar" class="menubar">
			<div id="boardmenu" class="boardmenu">
        [<a href="/">Home</a>]
        [<a href="/bans/">Bans</a>]
        [<a href="/manage/">Manage</a>]
			</div>
    </div>
    <?=$this->render(__ROOT__ . '/common/templates/header.phtml', ['h_title' => 'Bans', 'h_subtitle' => 'Public list of latest bans'])?>

    <div class="page-root container-centered">
      <div class="box-container">
        <div class="box">
          <div class="box-title">Bans</div>
          <div class="box-content">
            <table>
              <thead>
                <tr>
                  <th>id</th>
                  <th>ip</th>
                  <th>timestamp</th>
                  <th>expire</th>
                  <th>reason</th>
                </tr>
              </thead>
              <tbody>
                <?php
                  foreach ($bans as $ban) {
                    echo "
                      <tr>
                        <td>{$ban->id}</td>
                        <td>{$ban->redact_ip()}</td>
                        <td>{$ban->fmt_timestamp()}</td>
                        <td>{$ban->fmt_expire()}</td>
                        <td>{$ban->reason}</td>
                        <td>{$ban->imported}</td>
                      </tr>
                    ";
                  }
                ?>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
    <hr>
    <div class="container-centered">
      <?=$this->render(__ROOT__ . '/common/templates/footer.phtml')?>
    </div>
  </body>
</html>
