<!DOCTYPE html>
<html>
  <head>
    <?=$this->render(__DIR__ . '/meta.phtml')?>
    <?=$this->render(__DIR__ . '/styles.phtml')?>
    <?=$this->render(__DIR__ . '/scripts.phtml')?>
    <title><?=htmlspecialchars($error_type, ENT_QUOTES, 'UTF-8')?></title>
  </head>
  <body>
    <?=$this->render(__ROOT__ . '/common/templates/header.phtml', ['h_title' => 'Error', 'h_subtitle' => "<a href='/'>Return</a>"])?>
    <hr>
    <div class="page-root container-centered">
      <div class="box-container">
        <div class="box">
          <div class="box-title">ERR <?= htmlspecialchars($error_type, ENT_QUOTES, 'UTF-8') ?> :: MSG <?= htmlspecialchars($error_message, ENT_QUOTES, 'UTF-8') ?></div>
          <div class="box-content">
            <div class="container-centered">
              <?php
                if (isset($error_image) && !empty($error_image)) {
                  $error_image_escaped = htmlspecialchars($error_image, ENT_QUOTES, 'UTF-8');
                  echo "<img src='{$error_image_escaped}' width='100%' height='100%'>";
                } else {
                  echo 'something went wrong...';
                }
              ?>
            </div>
          </div>
        </div>
      </div>
    <hr>
    <div class="container-centered">
      <?=$this->render(__ROOT__ . '/common/templates/footer.phtml')?>
    </div>
  </body>
</html>
