<!DOCTYPE html>
<html>
  <head>
    <?=$this->render(__DIR__ . '/meta.phtml')?>
    <?=$this->render(__DIR__ . '/styles.phtml')?>
    <?=$this->render(__DIR__ . '/scripts.phtml')?>
    <title><?=$error_type?></title>
  </head>
  <body>
    <?=$this->render(__ROOT__ . '/common/templates/header.phtml', ['h_title' => $error_type, 'h_subtitle' => $error_message])?>
    <hr>
    <?php
      if (isset($error_image) && !empty($error_image)) {
        echo "<div class='container-centered'>
          <img src='{$error_image}' width='50%' height='50%'>
        </div>";
      }
    ?>
    <hr>
    <div class="container-centered">
      <?=$this->render(__ROOT__ . '/common/templates/footer.phtml')?>
    </div>
  </body>
</html>
