<link rel="stylesheet" type="text/css" href="/css/index.css?mb_version=<?=MB_VERSION?>">
<link rel="stylesheet" type="text/css" href="/css/mobile.css?mb_version=<?=MB_VERSION?>">
<?php
  $mb_style = MB_STYLES[0];
  if (isset($_COOKIE["miniboard/style"])) {
    $mb_style_cookie = $_COOKIE["miniboard/style"];
  
    if (in_array($mb_style_cookie, MB_STYLES)) {
      $mb_style = $mb_style_cookie;
    }
  }

  echo "<link rel=\"stylesheet\" type=\"text/css\" href=\"/css/{$mb_style}.css?mb_version=" . MB_VERSION . "\">";
?>
<link rel="stylesheet" type="text/css" href="/css/flags.css?mb_version=<?=MB_VERSION?>">
<link rel="stylesheet" type="text/css" href="/dist/tegaki/tegaki.css?mb_version=<?=MB_VERSION?>">

<?= minichan\core\App::get_instance()->run_hooks('common.styles'); ?>
