FROM php:8.0.3-cli-alpine3.12

# install and configure php
RUN apk add --no-cache bash ffmpeg exiftool
RUN mv $PHP_INI_DIR/php.ini-development $PHP_INI_DIR/php.ini
ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
RUN chmod +x /usr/local/bin/install-php-extensions && \
    sync && \
    install-php-extensions @composer imagick pdo pdo_mysql xdebug redis && \
    docker-php-ext-enable imagick pdo_mysql xdebug redis
COPY docker/miniboard/php/conf.d/miniboard.ini $PHP_INI_DIR/conf.d/
COPY docker/miniboard/php/conf.d/xdebug.ini $PHP_INI_DIR/conf.d/

# install miniboard
COPY . /app
WORKDIR /app
RUN composer install --no-interaction && \
    chown www-data:www-data -R public

# runtime setup
EXPOSE 80
ENV MB_ENV dev

CMD [ "php", "-S", "0.0.0.0:80", "-t", "public" ]
