FROM php:8.0.3-cli-alpine3.12

WORKDIR /

RUN apk update && apk add --no-cache bash ffmpeg exiftool
RUN mv $PHP_INI_DIR/php.ini-development $PHP_INI_DIR/php.ini
ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
RUN chmod +x /usr/local/bin/install-php-extensions && \
    sync && \
    install-php-extensions @composer gd pdo pdo_mysql xdebug && \
    docker-php-ext-enable pdo_mysql xdebug
COPY . /app

WORKDIR /app

RUN composer install && chown www-data:www-data -R public
EXPOSE 80
ENV MB_ENV dev

CMD [ "php", "-d", "upload_max_filesize=32M", "-d", "post_max_size=64M", "-S", "0.0.0.0:80", "-t", "public" ]
