<!DOCTYPE html>
<html>
  <head>
    <?=$this->render(__ROOT__ . '/common/templates/meta.phtml')?>
    <?=$this->render(__ROOT__ . '/common/templates/styles.phtml')?>
    <?=$this->render(__ROOT__ . '/common/templates/scripts.phtml')?>
    <title>Login</title>
  </head>
  <body>
    <?=$this->render(__ROOT__ . '/common/templates/header.phtml', ['h_title' => 'Manage', 'h_subtitle' => 'Login'])?>
    <hr>
    <div class="container-centered">
      <?=$this->render(__DIR__ . '/components/loginform.phtml')?>
    </div>
    <hr>
    <div class="container-centered">
      <?=$this->render(__ROOT__ . '/common/templates/footer.phtml')?>
    </div>
  </body>
</html>
