<form id="deleteform" class="deleteform" method="post" action="/<?=$board['id']?>/delete">
  <?=funcs_common_csrf_field()?>
  <?php
    foreach ($threads as $thread) {
      echo $this->render(__DIR__ . '/post_op.phtml', ['context' => $context, 'board' => $board, 'post' => $thread]) . '<hr>';
    }
  ?>
  <div class="deleteform-group">
    <label for="delete"><?=__('delete.title')?></label>
    <input id="deleteform-password" type="password" name="password" placeholder="<?=__('delete.password')?>" size="8">
    <input type="submit" value="<?=__('delete.submit')?>">
  </div>
</form>
