<div id="menubar" class="menubar">
  <div class="boardlist desktop">
    [ <?php
      foreach (MB_BOARDS as $key => $board_cfg) {
        if (isset($board_cfg['hidden']) && $board_cfg['hidden'] == true) {
          continue;
        }

        echo "<a href='/{$board_cfg['id']}/'>{$board_cfg['id']}</a>";
        if ($key !== array_key_last(MB_BOARDS)) {
          echo ' / ';
        }
      }
    ?> ]
  </div>
  <div class="boardlist mobile">
    <?php
      $options = '<option value=""></option>';
      foreach (MB_BOARDS as $key => $board_cfg) {
        if (isset($board_cfg['hidden']) && $board_cfg['hidden'] == true) {
          continue;
        }

        $selected = '';
        if ($board_cfg['id'] === $board_id) {
          $selected = ' selected';
        }

        $options .= "<option value='{$board_cfg['id']}'{$selected}>/{$board_cfg['id']}/ - {$board_cfg['name']}</option>";
      }

      echo "
        <select id='boardselect-mobile'>{$options}</select>
      ";
    ?>
  </div>

  <div id="boardmenu-desktop" class="boardmenu desktop">
    [<a id="boardmenu-desktop-home" href="/"><?=__('nav.home')?></a>]
    [<a id="boardmenu-desktop-hidden" href="/<?=$board_id?>/hidden/"><?=__('nav.hidden')?></a>]
    [<a id="boardmenu-desktop-catalog" href="/<?=$board_id?>/catalog/"><?=__('nav.catalog')?></a>]
    [<a id="boardmenu-desktop-gallery" href="#"><?=__('nav.gallery')?></a>]
    [<a id="boardmenu-desktop-settings" href="#"><?=__('nav.settings')?></a>]
    [<a id="boardmenu-desktop-manage" href="/manage/"><?=__('nav.manage')?></a>]
  </div>

  <div id="boardmenu-mobile" class="boardmenu mobile">
    <a id="boardmenu-mobile-home" href="/"><img class="icon" src="/icons/home.svg"></a>
    <a id="boardmenu-mobile-hidden" href="/<?=$board_id?>/hidden/"><img class="icon" src="/icons/eye-slash.svg"></a>
    <a id="boardmenu-mobile-catalog" href="/<?=$board_id?>/catalog/"><img class="icon" src="/icons/squares-2x2.svg"></a>
    <a id="boardmenu-mobile-gallery" href="#"><img class="icon" src="/icons/photo.svg"></a>
    <a id="boardmenu-mobile-settings" href="#"><img class="icon" src="/icons/wrench.svg"></a>
    <a id="boardmenu-mobile-manage" href="/manage/"><img class="icon" src="/icons/users.svg"></a>
  </div>
  <?=$this->render(__ROOT__ . '/common/templates/stylepicker.phtml')?>
</div>
