<div class="post reply preview">
  <div class="reply">
    <div class="post-info">
      <label>
        <input type="checkbox" disabled>
        <span class="post-subject"><?=$error_code?></span>
        <span class='post-name'><?=$error_title?></span>
      </label>
    </div>
    <div class="post-message-wrapper">
      <div class="post-message">
        <?=$message?>
      </div>
    </div>
  </div>
</div>
