<div class="post-container reply-container<?=!empty($post['hidden']) ? ' reply-hidden' : ''?>" id="rc_<?=$post['board_id']?>-<?=$post['post_id']?>">
  <div class="post-dash">>></div>
<?php if (!empty($post['hidden'])): ?>
  <div class="post reply post-stub" id="<?=$post['board_id']?>-<?=$post['post_id']?>" data-parent_id="<?=$post['parent_id']?>">
    <div class="post-info">
      <span class="post-number"><?=$reply_number?></span>
      <span class="post-id">
        No.<?=$post['post_id']?>
      </span>
      <span class="post-hidden-label">Post hidden</span>
      <a href="#" class="dd-menu-btn" data-board_id="<?=$post['board_id']?>" data-parent_id="<?=$post['parent_id']?>" data-id="<?=$post['post_id']?>" data-cmd="post-menu">▶</a>
    </div>
  </div>
<?php else: ?>
  <div class="post reply" id="<?=$post['board_id']?>-<?=$post['post_id']?>" data-parent_id="<?=$post['parent_id']?>">
    <div class="post-info">
      <label>
        <span class="post-number"><?=$reply_number?></span>
        <input type="checkbox" name="delete[]" value="<?=$post['board_id']?>/<?=$post['post_id']?>">
        <span class="post-subject"><?=$post['subject']?></span>
        <?=$post['nameblock']?>
      </label>
      <span class="post-id">
        <a href="/<?=$post['board_id']?>/<?=$post['parent_id']?>/#<?=$post['board_id']?>-<?=$post['post_id']?>">No.</a><a href="/<?=$post['board_id']?>/<?=$post['parent_id']?>/#q<?=$post['post_id']?>"><?=$post['post_id']?></a>
      </span>
      <a href="#" class="dd-menu-btn" data-board_id="<?=$post['board_id']?>" data-parent_id="<?=$post['parent_id']?>" data-id="<?=$post['post_id']?>" data-cmd="post-menu">▶</a>
    </div>
    <?=$this->render(__DIR__ . '/post_file.phtml', ['context' => 'normal', 'post' => $post])?>
    <div class="post-message-wrapper">
      <div class="post-message">
        <?php
          if ($context === 'thread' || !isset($post['message_truncated'])) {
            echo $post['message_rendered'];
          } else {
            echo $post['message_truncated'];
            echo '<br><br><span class="truncated">Post truncated. Click reply to view.</span>';
          }
        ?>
      </div>
    </div>
  </div>
<?php endif; ?>
</div>
