<div class="thread" id="thread_<?=$post['board_id']?>-<?=$post['post_id']?>">
  <div class="post-container" id="pc_<?=$post['board_id']?>-<?=$post['post_id']?>">
    <div class="post op" id="<?=$post['board_id']?>-<?=$post['post_id']?>">
      <?=$this->render(__DIR__ . '/post_file.phtml', ['context' => 'normal', 'post' => $post])?>
      <div class="post-info">
        <label>
          <input type="checkbox" name="delete[]" value="<?=$post['board_id']?>/<?=$post['post_id']?>">
          <?php
            if ($board['type'] === 'main') {
              echo "<span class='post-board'>/{$post['board_id']}/</span>";
            }
          ?>
          <span class="post-subject"><?=$post['subject']?></span>
          <?=$post['nameblock']?>
        </label>
        <span class="post-id">
          <a href="/<?=$post['board_id']?>/<?=$post['post_id']?>/#<?=$post['board_id']?>-<?=$post['post_id']?>">No.</a><a href="/<?=$post['board_id']?>/<?=$post['post_id']?>/#q<?=$post['post_id']?>"><?=$post['post_id']?></a>
        </span>
        <?php
          $t_stickied = __('post.stickied');
          $t_locked = __('post.locked');
          if ($post['stickied'] === 1) {
            echo "<img src='/static/sticky.png' alt='{$t_stickied}' title='{$t_stickied}' width='16' height='16'>";
          }
          if ($post['locked'] === 1) {
            echo "<img src='/static/lock.png' alt='{$t_locked}' title='{$t_locked}' width='16' height='16'>";
          }
        ?>
        <?php
          if ($context === 'board') {
            $t_reply = __('post.reply');
            echo "[<a class='post-reply-link' href='/{$post['board_id']}/{$post['post_id']}/'>{$t_reply}</a>]";
          }
        ?>
        <a href="#" class="dd-menu-btn" data-board_id="<?=$post['board_id']?>" data-id="<?=$post['post_id']?>" data-cmd="post-menu">▶</a>
      </div>
      <div class="post-message-wrapper">
        <div class="post-message">
          <?php
            if ($context === 'thread' || !isset($post['message_truncated'])) {
              echo $post['message_rendered'];
            } else {
              echo $post['message_truncated'];
              echo '<br><br><span class="truncated">' . __('post.truncated') . '</span>';
            }
          ?>
        </div>
      </div>
    </div>
  </div>
  <?php
    if ($context === 'board') {
      $replies_omitted = $post['replies_n'] - count($post['replies']);
      if ($replies_omitted > 0) {
        echo "<span class='omitted'>" . __('post.replies_omitted', ['count' => $replies_omitted]) . "</span>";
      }
    }
  ?>
  <?php
    $reply_offset = ($context === 'board') ? $post['replies_n'] - count($post['replies']) : 0;
    foreach ($post['replies'] as $key => $reply) {
      echo $this->render(__DIR__ . '/post_reply.phtml', ['context' => $context, 'post' => $reply, 'reply_number' => $reply_offset + $key + 1]);
    }
  ?>
</div>
