<form id="form-post" class="form-post form" method="post" action="<?=$action?>" enctype="multipart/form-data">
  <?=funcs_common_csrf_field()?>
  <table>
    <tbody>
      <tr>
        <td class="form-label">
          <label for="name"><?=__('form.name')?></label>
        </td>
        <td>
          <input type="text" name="name">
        </td>
      </tr>
      <tr>
        <td class="form-label">
          <label for="email"><?=__('form.email')?></label>
        </td>
        <td>
          <input type="text" name="email" autocomplete="off">
        </td>
      </tr>
      <?php
        if (funcs_common_is_logged_in()) {
          $t_mod_options = __('form.mod_options');
          $t_capcode = __('form.capcode');
          if ($board['req_role'] == null) {
            echo "
            <tr>
              <td class='form-label'>
                <label for='mod-options'>{$t_mod_options}</label>
              </td>
              <td>
                <label>
                  <input type='checkbox' name='capcode' value='1'>
                  {$t_capcode}
                </label>
              </td>
            </tr>
            ";
          } else {
            echo "
            <tr>
              <td class='form-label'>
                <label for='mod-options'>{$t_mod_options}</label>
              </td>
              <td>
                <label>
                  <input type='checkbox' name='capcode' value='1' checked disabled>
                  {$t_capcode}
                </label>
              </td>
            </tr>
            ";
          }
        }
      ?>
      <tr>
        <td class="form-label">
          <label for="subject"><?=__('form.subject')?></label>
        </td>
        <td>
          <input type="text" name="subject" autocomplete="off">
          <input type="submit" name="submit" value="<?=__('form.submit')?>">
        </td>
      </tr>
      <tr>
        <td class="form-label">
          <label for="message"><?=__('form.message')?></label>
        </td>
        <td>
          <button type="button" class="format-btn" data-format="b"><b>b</b></button><!--
       --><button type="button" class="format-btn" data-format="i"><i>i</i></button><!--
       --><button type="button" class="format-btn" data-format="u"><u>u</u></button><!--
       --><button type="button" class="format-btn" data-format="s"><s>s</s></button><!--
       --><button type="button" class="format-btn" data-format="sup">sup</button><!--
       --><button type="button" class="format-btn" data-format="sub">sub</button><!--
       --><button type="button" class="format-btn" data-format="code">code</button><!--
       --><button type="button" class="format-btn" data-format="spoiler">spoiler</button>
          <br>
          <textarea id="form-post-message" class="form-post-message" name="message" autocomplete="off" maxlength="8192"></textarea>
        </td>
      </tr>
      <?php
        // captcha check
        if (!funcs_common_is_logged_in()) {
          if ($context === 'board' && MB_CAPTCHA_THREAD || $context === 'thread' && MB_CAPTCHA_REPLY) {
            $captcha = MB_CAPTCHA_HCAPTCHA_SITE;
            $t_captcha = __('form.captcha');

            echo "
              <tr>
                <td class='form-label'>
                  <label for='captcha'>{$t_captcha}</label>
                </td>
                <td>
                  <div id='form-post-captcha' class='h-captcha' data-sitekey='{$captcha}'></div>
                </td>
              </tr>
            ";
          }
        }

        // board select
        if ($board['type'] === 'main') {
          $options = '<option value=""></option>';
          foreach (MB_BOARDS as $key => $val) {
            if ($val['type'] === 'main') {
              continue;
            }

            $options .= "<option value='{$key}'>/{$key}/ - {$val['name']}</option>";
          }

          $t_board = __('form.board');
          echo "
            <tr>
              <td class='form-label'>
                <label for='board'>{$t_board}</label>
              </td>
              <td>
                <select id='board' name='board'>{$options}</select>
              </td>
            </tr>
          ";
        }

        // file
        if (!isset($board['text']) || $board['text'] == false) {
          $t_file = __('form.file');
          $t_draw = __('form.draw');
          $t_file_options = __('form.file_options');
          $t_spoiler = __('form.spoiler');
          $t_no_filename = __('form.no_filename');
          $t_embed = __('form.embed');
          echo "
            <tr>
              <td class='form-label'>
                <label for='file'>{$t_file}</label>
              </td>
              <td>
                <input id='form-file' type='file' name='file[]' autocomplete='off' size='35'>
                <button id='form-draw' type='button' name='draw'>{$t_draw}</button>
              </td>
            </tr>
            <tr>
              <td class='form-label'>
                <label for='file-options'>{$t_file_options}</label>
              </td>
              <td>
                <label>
                  <input type='checkbox' name='spoiler' value='1'>
                  {$t_spoiler}
                </label>
                <label>
                  <input type='checkbox' name='anonfile' value='1'>
                  {$t_no_filename}
                </label>
              </td>
            </tr>
            <tr>
              <td class='form-label'>
                <label for='embed'>{$t_embed}</label>
              </td>
              <td>
                <input type='text' name='embed' autocomplete='off'>
              </td>
            </tr>
          ";
        }
      ?>
      <tr>
        <td class="form-label">
          <label for="password"><?=__('form.password')?></label>
        </td>
        <td>
          <input id="form-post-password" type="password" name="password">
        </td>
      </tr>
      <?php
        if ($board['type'] !== 'main' && (!isset($board['text']) || $board['text'] == false)) {
          $info_exts = strtoupper(implode(', ', array_unique(array_column($board['mime_ext_types'], 0))));
          $info_embs = strtoupper(implode(', ', array_keys($board['embed_types'])));
          $info_fsize = funcs_common_human_filesize($board['maxkb'] * 1000);
          $info_msize = $board['max_width'] . 'x' . $board['max_height'];

          $t_supported_files = __('form.supported_files', ['types' => "<span id='form-post-info-exts'>{$info_exts}</span>"]);
          $t_supported_embeds = __('form.supported_embeds', ['types' => "<span id='form-post-info-embeds'>{$info_embs}</span>"]);
          $t_max_filesize = __('form.max_filesize', ['size' => "<span id='form-post-info-fsize'>{$info_fsize}</span>"]);
          $t_thumb_info = __('form.thumb_info', ['size' => "<span id='form-post-info-msize'>{$info_msize}</span>"]);

          echo "
            <tr>
              <td class='form-list' colspan='2'>
                <ul>
                  <li>{$t_supported_files}</li>
                  <li>{$t_supported_embeds}</li>
                  <li>{$t_max_filesize}</li>
                  <li>{$t_thumb_info}</li>
                </ul>
              </td>
            </tr>
          ";
        }
      ?>
    </tbody>
  </table>
</form>
