<form id="form-report" class="form-report form" method="post">
  <?=funcs_common_csrf_field()?>
  <table>
    <tbody>
      <tr>
        <td class="form-label">
          <label><?=__('report.notice')?></label>
        </td>
        <td>
          <?=__('report.info', ['post_id' => $post['post_id'], 'board_id' => $post['board_id']])?>
          <?=__('report.warning')?>
        </td>
      </tr>
      <tr>
        <td class="form-label">
          <label for="type"><?=__('report.type')?></label>
        </td>
        <td>
          <?php
            $options = '<option value=""></option>';
            foreach (MB_REPORT_TYPES as $key => $val) {
              $options .= "<option value='{$key}'>{$val}</option>";
            }

            echo "
              <select id='type' name='type'>{$options}</select>
            ";
          ?>
          <button type="submit"><?=__('form.submit')?></button>
        </td>
      </tr>
      <tr>
        <td class="form-label">
          <label for="reason"><?=__('report.reason')?></label>
        </td>
        <td>
          <textarea id="reason" name="reason" rows="3" maxlength="500" placeholder="<?=__('report.reason_placeholder')?>"></textarea>
        </td>
      </tr>
      <?php
        if (MB_CAPTCHA_REPORT) {
          $captcha = MB_CAPTCHA_HCAPTCHA_SITE;
          $t_captcha = __('form.captcha');

          echo "
            <tr>
              <td class='form-label'>
                <label for='captcha'>{$t_captcha}</label>
              </td>
              <td>
                <div class='h-captcha' data-sitekey='{$captcha}'></div>
              </td>
            </tr>
          ";
        }
      ?>
    </tbody>
  </table>
</form>
